In [30]:
import pandas

In [32]:
df_basics = pandas.read_csv('./title.basics.csv')

In [55]:
df_basics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489949 entries, 0 to 489948
Data columns (total 9 columns):
tconst            489949 non-null object
titleType         489949 non-null object
primaryTitle      489949 non-null object
originalTitle     489949 non-null object
isAdult           489949 non-null int64
startYear         489949 non-null int64
endYear           489949 non-null object
runtimeMinutes    489949 non-null int64
genres            489949 non-null object
dtypes: int64(3), object(6)
memory usage: 33.6+ MB

In [40]:
df_genres_of = df_basics[['tconst', 'genres']]

In [41]:
df_genres_of.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489949 entries, 0 to 489948
Data columns (total 2 columns):
tconst    489949 non-null object
genres    489949 non-null object
dtypes: object(2)
memory usage: 7.5+ MB

In [38]:
df_genres_of = df_genres_of.drop_duplicates()

In [42]:
df_genres_of.to_csv('genreOf.csv', index=False)

In [44]:
df_basics_without_genres = df_basics[['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult', 'startYear', 'endYear', 'runtimeMinutes']]

In [45]:
df_basics_without_genres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489949 entries, 0 to 489948
Data columns (total 8 columns):
tconst            489949 non-null object
titleType         489949 non-null object
primaryTitle      489949 non-null object
originalTitle     489949 non-null object
isAdult           489949 non-null int64
startYear         489949 non-null int64
endYear           489949 non-null object
runtimeMinutes    489949 non-null int64
dtypes: int64(3), object(5)
memory usage: 29.9+ MB

In [46]:
df_basics_without_genres.to_csv('movie.csv', index=False)

In [47]:
df_genres = df_genres_of[['genres']]

In [48]:
df_genres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489949 entries, 0 to 489948
Data columns (total 1 columns):
genres    489949 non-null object
dtypes: object(1)
memory usage: 3.7+ MB

In [52]:
df_genres_nodup = df_genres.drop_duplicates()

In [53]:
df_genres_nodup.to_csv('genres.csv', index=False)

In [54]:
df_genres_nodup.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1841 entries, 0 to 488531
Data columns (total 1 columns):
genres    1841 non-null object
dtypes: object(1)
memory usage: 28.8+ KB

In [56]:
df_basics_without_genres.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,tt0000009,short,Miss Jerry,Miss Jerry,0,1894,\N,40
1,tt0000446,short,Kit Carson,Kit Carson,0,1903,\N,21
2,tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,0,1906,\N,70
3,tt0000591,movie,The Prodigal Son,L'enfant prodigue,0,1907,\N,90
4,tt0000679,movie,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,0,1908,\N,120

In [59]:
df_person = pandas.read_csv('./name.basics.csv')

In [60]:
df_person.head()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0053137,tt0031983,tt0050419,tt0072308"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0037382,tt0117057,tt0071877,tt0038355"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,soundtrack,music_department","tt0056404,tt0057345,tt0054452,tt0049189"
3,nm0000004,John Belushi,1949,1982,"actor,soundtrack,writer","tt0072562,tt0078723,tt0080455,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0069467,tt0083922,tt0060827,tt0050986"

In [62]:
writers = df_person.loc[df_person['primaryProfession'].str.contains("writer", case=False)]

ValueError: cannot index with vector containing NA / NaN values

In [64]:
df_person_pP_not_null = df_person[df_person['primaryProfession'].notnull()]

In [66]:
df_person_pP_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 996906 entries, 0 to 1106615
Data columns (total 6 columns):
nconst               996906 non-null object
primaryName          996906 non-null object
birthYear            996906 non-null object
deathYear            996906 non-null object
primaryProfession    996906 non-null object
knownForTitles       996906 non-null object
dtypes: object(6)
memory usage: 53.2+ MB

In [68]:
df_person.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1106616 entries, 0 to 1106615
Data columns (total 6 columns):
nconst               1106616 non-null object
primaryName          1106616 non-null object
birthYear            1106616 non-null object
deathYear            1106616 non-null object
primaryProfession    996906 non-null object
knownForTitles       1106616 non-null object
dtypes: object(6)
memory usage: 50.7+ MB

In [70]:
writers = df_person_pP_not_null.loc[df_person_pP_not_null['primaryProfession'].str.contains("writer", case=False)]

In [71]:
writers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 235204 entries, 3 to 1106611
Data columns (total 6 columns):
nconst               235204 non-null object
primaryName          235204 non-null object
birthYear            235204 non-null object
deathYear            235204 non-null object
primaryProfession    235204 non-null object
knownForTitles       235204 non-null object
dtypes: object(6)
memory usage: 12.6+ MB

In [72]:
writers.head(50)

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
3,nm0000004,John Belushi,1949,1982,"actor,soundtrack,writer","tt0072562,tt0078723,tt0080455,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0069467,tt0083922,tt0060827,tt0050986"
18,nm0000019,Federico Fellini,1920,1993,"writer,director,assistant_director","tt0050783,tt0047528,tt0071129,tt0056801"
23,nm0000024,John Gielgud,1904,2000,"actor,writer,director","tt0071877,tt0082031,tt0117631,tt0045943"
26,nm0000027,Alec Guinness,1914,2000,"actor,soundtrack,writer","tt0076759,tt0051739,tt0050212,tt0041546"
30,nm0000031,Katharine Hepburn,1907,2003,"actress,soundtrack,writer","tt0043265,tt0063227,tt0032904,tt0082846"
31,nm0000032,Charlton Heston,1923,2008,"actor,director,writer","tt0052618,tt0063442,tt0049833,tt0070723"
35,nm0000036,Buster Keaton,1895,1966,"actor,writer,director","tt0015324,tt0016332,tt0017925,tt0019421"
39,nm0000040,Stanley Kubrick,1928,1999,"writer,director,producer","tt0120663,tt0072684,tt0066921,tt0062622"
40,nm0000041,Akira Kurosawa,1910,1998,"writer,director,assistant_director","tt0089881,tt0080979,tt0051808,tt0057565"
44,nm0000045,Bruce Lee,1940,1973,"actor,writer,miscellaneous","tt0070034,tt0067824,tt0068767,tt0068935"
45,nm0000046,Vivien Leigh,1913,1967,"actress,soundtrack,writer","tt0044081,tt0033238,tt0034272,tt0031381"
47,nm0000048,Peter Lorre,1904,1964,"actor,soundtrack,writer","tt0036613,tt0034583,tt0033870,tt0022100"
49,nm0000050,Groucho Marx,1890,1977,"soundtrack,actor,writer","tt0028772,tt0026778,tt0023969,tt0023027"
50,nm0000051,James Mason,1909,1984,"actor,producer,writer","tt0084855,tt0056193,tt0053125,tt0047522"
53,nm0000054,Marilyn Monroe,1926,1962,"soundtrack,actress,writer","tt0050861,tt0048605,tt0045810,tt0053291"
63,nm0000064,Edward G. Robinson,1893,1973,"actor,soundtrack,writer","tt0040506,tt0070723,tt0036775,tt0038991"
72,nm0000073,Shirley Temple,1928,2014,"actress,soundtrack,writer","tt0030657,tt0028118,tt0016029,tt0031580"
75,nm0000076,François Truffaut,1932,1984,"writer,director,producer","tt0075860,tt0070460,tt0055032,tt0053198"
79,nm0000080,Orson Welles,1915,1985,"actor,director,writer","tt0038991,tt0040525,tt0033467,tt0052311"
82,nm0000083,Alan Miller,\N,\N,"editor,writer,director","tt0969216,tt5969604,tt0424773,tt0320978"
85,nm0000086,Louis de Funès,1914,1983,"actor,writer,soundtrack","tt0079200,tt0064425,tt0069747,tt0074103"
87,nm0000088,Aleksey Korenev,1927,1995,"director,writer,assistant_director","tt0063752,tt0068304,tt0100069,tt0191104"
89,nm0000090,Armin Mueller-Stahl,1930,\N,"actor,director,writer","tt0139809,tt0117631,tt0963178,tt0765443"
90,nm0000091,Gérard Pirès,1942,\N,"director,writer,actor","tt0152930,tt0282552,tt0064297,tt0374627"
91,nm0000092,John Cleese,1939,\N,"actor,writer,producer","tt0071853,tt0085959,tt0095159,tt0063929"
93,nm0000094,J. Reifel,\N,\N,writer,"tt0116030,tt0117915,tt0118886,tt0118631"
94,nm0000095,Woody Allen,1935,\N,"writer,director,actor","tt0075686,tt0097123,tt0079522,tt0091167"
99,nm0000100,Rowan Atkinson,1955,\N,"actor,writer,producer","tt1634122,tt0110357,tt0118689,tt0274166"
100,nm0000101,Dan Aykroyd,1952,\N,"writer,actor,producer","tt0080455,tt0118747,tt0087332,tt0097428"
103,nm0000104,Antonio Banderas,1960,\N,"actor,soundtrack,writer","tt0112851,tt0120657,tt0120746,tt1189073"
107,nm0000108,Luc Besson,1959,\N,"writer,producer,director","tt0119116,tt0110413,tt2872732,tt0100263"
115,nm0000116,James Cameron,1954,\N,"writer,producer,director","tt0090605,tt0120338,tt0499549,tt0103064"
117,nm0000118,John Carpenter,1948,\N,"soundtrack,writer,composer","tt0096256,tt0077651,tt0080749,tt0082340"
119,nm0000120,Jim Carrey,1962,\N,"actor,writer,producer","tt0338013,tt0315327,tt0110475,tt0109040"
121,nm0000122,Charles Chaplin,1889,1977,"writer,soundtrack,actor","tt0032553,tt0027977,tt0044837,tt0018773"
126,nm0000127,Wes Craven,1939,2015,"writer,producer,director","tt0111686,tt0117571,tt0087800,tt0105121"
130,nm0000131,John Cusack,1966,\N,"actor,producer,writer","tt0450385,tt0146882,tt0119229,tt0098258"
147,nm0000148,Harrison Ford,1942,\N,"actor,writer,producer","tt0106977,tt0118571,tt0082971,tt0076759"
154,nm0000155,Whoopi Goldberg,1955,\N,"actress,producer,writer","tt0105417,tt0099653,tt0108147,tt0088939"
158,nm0000159,Teri Hatcher,1964,\N,"actress,soundtrack,writer","tt0410975,tt0106057,tt0227538,tt0120347"
159,nm0000160,Ethan Hawke,1970,\N,"actor,writer,producer","tt0112471,tt0139654,tt0381681,tt2209418"
161,nm0000162,Anne Heche,1969,\N,"actress,writer,producer","tt0120828,tt0251160,tt0120885,tt0119008"
164,nm0000165,Ron Howard,1954,\N,"actor,producer,writer","tt0112384,tt0268978,tt0088933,tt0367279"
174,nm0000175,Stephen King,1947,\N,"writer,producer,actor","tt0091499,tt0111161,tt0324864,tt0083767"
179,nm0000180,David Lean,1908,1991,"editor,director,writer","tt0056172,tt0050212,tt0087892,tt0059113"
183,nm0000184,George Lucas,1944,\N,"writer,producer,director","tt0066434,tt0076759,tt0082971,tt0069704"
185,nm0000186,David Lynch,1946,\N,"writer,director,producer","tt0460829,tt0166924,tt0098936,tt0105665"
187,nm0000188,Steve Martin,1945,\N,"writer,actor,soundtrack","tt0383216,tt0079367,tt0093886,tt0102250"
188,nm0000189,Jenny McCarthy Wahlberg,1972,\N,"actress,producer,writer","tt0455967,tt0131857,tt0134084,tt0327643"

In [73]:
director = df_person_pP_not_null.loc[df_person_pP_not_null['primaryProfession'].str.contains("director", case=False)]

In [74]:
director.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 205722 entries, 4 to 1106613
Data columns (total 6 columns):
nconst               205722 non-null object
primaryName          205722 non-null object
birthYear            205722 non-null object
deathYear            205722 non-null object
primaryProfession    205722 non-null object
knownForTitles       205722 non-null object
dtypes: object(6)
memory usage: 11.0+ MB

In [75]:
actor = df_person_pP_not_null.loc[df_person_pP_not_null['primaryProfession'].str.contains("actor", case=False)]

In [76]:
actor.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 346739 entries, 0 to 1106614
Data columns (total 6 columns):
nconst               346739 non-null object
primaryName          346739 non-null object
birthYear            346739 non-null object
deathYear            346739 non-null object
primaryProfession    346739 non-null object
knownForTitles       346739 non-null object
dtypes: object(6)
memory usage: 18.5+ MB

In [77]:
actress = df_person_pP_not_null.loc[df_person_pP_not_null['primaryProfession'].str.contains("actor", case=False)]

In [79]:
actress.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 346739 entries, 0 to 1106614
Data columns (total 6 columns):
nconst               346739 non-null object
primaryName          346739 non-null object
birthYear            346739 non-null object
deathYear            346739 non-null object
primaryProfession    346739 non-null object
knownForTitles       346739 non-null object
dtypes: object(6)
memory usage: 18.5+ MB

In [80]:
actress = actress.drop_duplicates()

In [81]:
actress.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 346739 entries, 0 to 1106614
Data columns (total 6 columns):
nconst               346739 non-null object
primaryName          346739 non-null object
birthYear            346739 non-null object
deathYear            346739 non-null object
primaryProfession    346739 non-null object
knownForTitles       346739 non-null object
dtypes: object(6)
memory usage: 18.5+ MB

In [82]:
writers.to_csv('writers.csv', index=False)

In [83]:
actor.to_csv('actors.csv', index=False)

In [84]:
actress.to_csv('actresses.csv', index=False)

In [87]:
director.to_csv('directors.csv', index=False)

In [88]:
director

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0069467,tt0083922,tt0060827,tt0050986"
7,nm0000008,Marlon Brando,1924,2004,"actor,soundtrack,director","tt0078788,tt0070849,tt0047296,tt0068646"
9,nm0000010,James Cagney,1899,1986,"actor,soundtrack,director","tt0031867,tt0029870,tt0035575,tt0042041"
18,nm0000019,Federico Fellini,1920,1993,"writer,director,assistant_director","tt0050783,tt0047528,tt0071129,tt0056801"
23,nm0000024,John Gielgud,1904,2000,"actor,writer,director","tt0071877,tt0082031,tt0117631,tt0045943"
31,nm0000032,Charlton Heston,1923,2008,"actor,director,writer","tt0052618,tt0063442,tt0049833,tt0070723"
32,nm0000033,Alfred Hitchcock,1899,1980,"director,producer,actor","tt0052357,tt0053125,tt0056869,tt0054215"
35,nm0000036,Buster Keaton,1895,1966,"actor,writer,director","tt0015324,tt0016332,tt0017925,tt0019421"
36,nm0000037,Gene Kelly,1912,1996,"soundtrack,actor,director","tt0041716,tt0053946,tt0043278,tt0045152"
39,nm0000040,Stanley Kubrick,1928,1999,"writer,director,producer","tt0120663,tt0072684,tt0066921,tt0062622"
40,nm0000041,Akira Kurosawa,1910,1998,"writer,director,assistant_director","tt0089881,tt0080979,tt0051808,tt0057565"
55,nm0000056,Paul Newman,1925,2008,"actor,producer,director","tt0084855,tt0257044,tt0054997,tt0061512"
58,nm0000059,Laurence Olivier,1907,1989,"actor,producer,director","tt0077269,tt0074860,tt0032976,tt0069281"
70,nm0000071,James Stewart,1908,1997,"actor,soundtrack,director","tt0052561,tt0052357,tt0032904,tt0031679"
75,nm0000076,François Truffaut,1932,1984,"writer,director,producer","tt0075860,tt0070460,tt0055032,tt0053198"
79,nm0000080,Orson Welles,1915,1985,"actor,director,writer","tt0038991,tt0040525,tt0033467,tt0052311"
82,nm0000083,Alan Miller,\N,\N,"editor,writer,director","tt0969216,tt5969604,tt0424773,tt0320978"
86,nm0000087,Elena Koreneva,1953,\N,"actress,casting_director,soundtrack","tt5847740,tt7529350,tt0080912,tt0122969"
87,nm0000088,Aleksey Korenev,1927,1995,"director,writer,assistant_director","tt0063752,tt0068304,tt0100069,tt0191104"
89,nm0000090,Armin Mueller-Stahl,1930,\N,"actor,director,writer","tt0139809,tt0117631,tt0963178,tt0765443"
90,nm0000091,Gérard Pirès,1942,\N,"director,writer,actor","tt0152930,tt0282552,tt0064297,tt0374627"
94,nm0000095,Woody Allen,1935,\N,"writer,director,actor","tt0075686,tt0097123,tt0079522,tt0091167"
96,nm0000097,Pamela Anderson,1967,\N,"actress,producer,director","tt0426592,tt0115624,tt0306047,tt0267913"
98,nm0000099,Patricia Arquette,1968,\N,"actress,soundtrack,director","tt0108399,tt0412175,tt1065073,tt0145531"
107,nm0000108,Luc Besson,1959,\N,"writer,producer,director","tt0119116,tt0110413,tt2872732,tt0100263"
109,nm0000110,Kenneth Branagh,1960,\N,"actor,producer,director","tt0116477,tt0097499,tt3402236,tt0107616"
110,nm0000111,Matthew Broderick,1962,\N,"actor,soundtrack,director","tt0086567,tt0091042,tt0126886,tt0395251"
113,nm0000114,Steve Buscemi,1957,\N,"actor,producer,director","tt0105236,tt4686844,tt0116282,tt0162346"
115,nm0000116,James Cameron,1954,\N,"writer,producer,director","tt0090605,tt0120338,tt0499549,tt0103064"
122,nm0000123,George Clooney,1961,\N,"actor,producer,director","tt0465538,tt0433383,tt1193138,tt1124035"
...,...,...,...,...,...,...
1106379,nm9988015,Jathin Sanker Raj,\N,\N,"cinematographer,producer,director","tt9536990,tt8731842"
1106385,nm9988424,Mohamed Hesham El-Rashidy,\N,\N,director,tt11493006
1106387,nm9988432,Kumar Gangappan,\N,\N,"art_director,art_department,production_designer","tt7738784,tt11216522,tt12472554,tt4701664"
1106389,nm9988460,David Sincere Aiken,\N,\N,"miscellaneous,director,actor","tt2473602,tt5030402"
1106391,nm9988491,Hicham Goullal,\N,\N,"assistant_director,miscellaneous,actor","tt15261252,tt1399664,tt6474236,tt6878882"
1106394,nm9988620,Titus I. Jackson,\N,\N,"cinematographer,director,writer","tt14030682,tt8732432,tt10627474"
1106422,nm9989001,Hyun-jin Ma,\N,\N,director,\N
1106429,nm9989068,Alice Zanini,\N,\N,"actress,assistant_director","tt5263880,tt7802180,tt9829282,tt11876490"
1106432,nm9989234,Happy BanMajra,\N,\N,"actor,assistant_director,production_manager","tt13823812,tt8733862,tt9537936,tt13134002"
1106439,nm9989277,Ryan Manley,\N,\N,"writer,director,casting_director","tt9615610,tt10749930,tt8734436,tt12264946"
1106443,nm9989631,Ellie Madden,\N,\N,"actress,assistant_director,stunts","tt8735428,tt9578208"
1106472,nm9990253,Dennis Mallen,\N,\N,"actor,producer,assistant_director","tt10746060,tt14140642,tt11388622,tt13650596"
1106492,nm9990679,Jude Okwudiafor Johnson,\N,\N,"producer,director,actor",\N
1106504,nm9991134,Hasshi,\N,\N,director,"tt9585424,tt9883900,tt13499386,tt8737918"
1106507,nm9991166,Brian Corso,\N,\N,"producer,director,executive","tt10047438,tt10832454,tt12803088,tt8738176"
1106516,nm9991402,Eric Sturges,\N,\N,"writer,producer,director","tt8734436,tt10802798,tt9078846,tt12264946"
1106517,nm9991404,Lisa Morel,\N,\N,"casting_director,producer,casting_department","tt8431754,tt10495908,tt9615610,tt8734436"
1106518,nm9991412,Taylor Katsanis,\N,\N,"director,actor,editor","tt12570876,tt9518982,tt12113548,tt8738578"
1106540,nm9992067,Robert DeBoucher,\N,\N,"editor,director,writer","tt11026620,tt10770776,tt8923476"
1106551,nm9992429,Haley Elizabeth Anderson,\N,\N,"director,writer,producer","tt11685322,tt11695844,tt14040068,tt12564956"
1106560,nm9992590,Rock White,\N,\N,"sound_department,camera_department,director","tt13750234,tt13601662,tt9188928,tt10399238"
1106563,nm9992639,Donnie Dodge,\N,\N,"director,writer,producer","tt11577388,tt10645746,tt8741948,tt14855720"
1106570,nm9992757,Bardia Zeinali,\N,\N,director,tt15285682
1106571,nm9992763,Pedro Flores Maldonado,\N,\N,"director,cinematographer","tt8742174,tt11734696"
1106573,nm9992818,Dudley Wineriter,\N,\N,"actor,producer,assistant_director","tt13814986,tt8742432,tt14136100,tt11183642"
1106574,nm9992819,Jennifer DiBlasio,\N,\N,"actress,assistant_director","tt13814986,tt13404996,tt14297962,tt14287002"
1106580,nm9992900,Tin Brendel,\N,\N,"writer,director,cinematographer",\N
1106582,nm9992905,Hepi Mita,\N,\N,"director,camera_department","tt8742574,tt1504286"
1106583,nm9992929,Krista Riihimaki,\N,\N,"director,writer,cinematographer",tt8742604
1106613,nm9993594,Adeoluwa Owu,\N,\N,"cinematographer,director,camera_department","tt16253232,tt16423720,tt15892144,tt13204624"

In [93]:
director['primaryProfession'].str.split(',', 2, expand=True)

                          0                   1                    2
4                    writer            director                actor
7                     actor          soundtrack             director
9                     actor          soundtrack             director
18                   writer            director   assistant_director
23                    actor              writer             director
31                    actor            director               writer
32                 director            producer                actor
35                    actor              writer             director
36               soundtrack               actor             director
39                   writer            director             producer
40                   writer            director   assistant_director
55                    actor            producer             director
58                    actor            producer             director
70                    actor          soundtrack             director
75                   writer            director             producer
79                    actor            director               writer
82                   editor              writer             director
86                  actress    casting_director           soundtrack
87                 director              writer   assistant_director
89                    actor            director               writer
90                 director              writer                actor
94                   writer            director                actor
96                  actress            producer             director
98                  actress          soundtrack             director
107                  writer            producer             director
109                   actor            producer             director
110                   actor          soundtrack             director
113                   actor            producer             director
115                  writer            producer             director
122                   actor            producer             director
...                     ...                 ...                  ...
1106379     cinematographer            producer             director
1106385            director                None                 None
1106387        art_director      art_department  production_designer
1106389       miscellaneous            director                actor
1106391  assistant_director       miscellaneous                actor
1106394     cinematographer            director               writer
1106422            director                None                 None
1106429             actress  assistant_director                 None
1106432               actor  assistant_director   production_manager
1106439              writer            director     casting_director
1106443             actress  assistant_director               stunts
1106472               actor            producer   assistant_director
1106492            producer            director                actor
1106504            director                None                 None
1106507            producer            director            executive
1106516              writer            producer             director
1106517    casting_director            producer   casting_department
1106518            director               actor               editor
1106540              editor            director               writer
1106551            director              writer             producer
1106560    sound_department   camera_department             director
1106563            director              writer             producer
1106570            director                None                 None
1106571            director     cinematographer                 None
1106573               actor            producer   assistant_director
1106574             actress  assistant_director                 None
1106580              writer            director      cinematographer
1106582            director   camera_department                 None
1106583            director              writer      cinematographer
1106613     cinematographer            director    camera_department

[205722 rows x 3 columns]

In [94]:
director

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles,pro1,pro2
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0069467,tt0083922,tt0060827,tt0050986",writer,"director,actor"
7,nm0000008,Marlon Brando,1924,2004,"actor,soundtrack,director","tt0078788,tt0070849,tt0047296,tt0068646",actor,"soundtrack,director"
9,nm0000010,James Cagney,1899,1986,"actor,soundtrack,director","tt0031867,tt0029870,tt0035575,tt0042041",actor,"soundtrack,director"
18,nm0000019,Federico Fellini,1920,1993,"writer,director,assistant_director","tt0050783,tt0047528,tt0071129,tt0056801",writer,"director,assistant_director"
23,nm0000024,John Gielgud,1904,2000,"actor,writer,director","tt0071877,tt0082031,tt0117631,tt0045943",actor,"writer,director"
31,nm0000032,Charlton Heston,1923,2008,"actor,director,writer","tt0052618,tt0063442,tt0049833,tt0070723",actor,"director,writer"
32,nm0000033,Alfred Hitchcock,1899,1980,"director,producer,actor","tt0052357,tt0053125,tt0056869,tt0054215",director,"producer,actor"
35,nm0000036,Buster Keaton,1895,1966,"actor,writer,director","tt0015324,tt0016332,tt0017925,tt0019421",actor,"writer,director"
36,nm0000037,Gene Kelly,1912,1996,"soundtrack,actor,director","tt0041716,tt0053946,tt0043278,tt0045152",soundtrack,"actor,director"
39,nm0000040,Stanley Kubrick,1928,1999,"writer,director,producer","tt0120663,tt0072684,tt0066921,tt0062622",writer,"director,producer"
40,nm0000041,Akira Kurosawa,1910,1998,"writer,director,assistant_director","tt0089881,tt0080979,tt0051808,tt0057565",writer,"director,assistant_director"
55,nm0000056,Paul Newman,1925,2008,"actor,producer,director","tt0084855,tt0257044,tt0054997,tt0061512",actor,"producer,director"
58,nm0000059,Laurence Olivier,1907,1989,"actor,producer,director","tt0077269,tt0074860,tt0032976,tt0069281",actor,"producer,director"
70,nm0000071,James Stewart,1908,1997,"actor,soundtrack,director","tt0052561,tt0052357,tt0032904,tt0031679",actor,"soundtrack,director"
75,nm0000076,François Truffaut,1932,1984,"writer,director,producer","tt0075860,tt0070460,tt0055032,tt0053198",writer,"director,producer"
79,nm0000080,Orson Welles,1915,1985,"actor,director,writer","tt0038991,tt0040525,tt0033467,tt0052311",actor,"director,writer"
82,nm0000083,Alan Miller,\N,\N,"editor,writer,director","tt0969216,tt5969604,tt0424773,tt0320978",editor,"writer,director"
86,nm0000087,Elena Koreneva,1953,\N,"actress,casting_director,soundtrack","tt5847740,tt7529350,tt0080912,tt0122969",actress,"casting_director,soundtrack"
87,nm0000088,Aleksey Korenev,1927,1995,"director,writer,assistant_director","tt0063752,tt0068304,tt0100069,tt0191104",director,"writer,assistant_director"
89,nm0000090,Armin Mueller-Stahl,1930,\N,"actor,director,writer","tt0139809,tt0117631,tt0963178,tt0765443",actor,"director,writer"
90,nm0000091,Gérard Pirès,1942,\N,"director,writer,actor","tt0152930,tt0282552,tt0064297,tt0374627",director,"writer,actor"
94,nm0000095,Woody Allen,1935,\N,"writer,director,actor","tt0075686,tt0097123,tt0079522,tt0091167",writer,"director,actor"
96,nm0000097,Pamela Anderson,1967,\N,"actress,producer,director","tt0426592,tt0115624,tt0306047,tt0267913",actress,"producer,director"
98,nm0000099,Patricia Arquette,1968,\N,"actress,soundtrack,director","tt0108399,tt0412175,tt1065073,tt0145531",actress,"soundtrack,director"
107,nm0000108,Luc Besson,1959,\N,"writer,producer,director","tt0119116,tt0110413,tt2872732,tt0100263",writer,"producer,director"
109,nm0000110,Kenneth Branagh,1960,\N,"actor,producer,director","tt0116477,tt0097499,tt3402236,tt0107616",actor,"producer,director"
110,nm0000111,Matthew Broderick,1962,\N,"actor,soundtrack,director","tt0086567,tt0091042,tt0126886,tt0395251",actor,"soundtrack,director"
113,nm0000114,Steve Buscemi,1957,\N,"actor,producer,director","tt0105236,tt4686844,tt0116282,tt0162346",actor,"producer,director"
115,nm0000116,James Cameron,1954,\N,"writer,producer,director","tt0090605,tt0120338,tt0499549,tt0103064",writer,"producer,director"
122,nm0000123,George Clooney,1961,\N,"actor,producer,director","tt0465538,tt0433383,tt1193138,tt1124035",actor,"producer,director"
...,...,...,...,...,...,...,...,...
1106379,nm9988015,Jathin Sanker Raj,\N,\N,"cinematographer,producer,director","tt9536990,tt8731842",cinematographer,"producer,director"
1106385,nm9988424,Mohamed Hesham El-Rashidy,\N,\N,director,tt11493006,director,NaN
1106387,nm9988432,Kumar Gangappan,\N,\N,"art_director,art_department,production_designer","tt7738784,tt11216522,tt12472554,tt4701664",art_director,"art_department,production_designer"
1106389,nm9988460,David Sincere Aiken,\N,\N,"miscellaneous,director,actor","tt2473602,tt5030402",miscellaneous,"director,actor"
1106391,nm9988491,Hicham Goullal,\N,\N,"assistant_director,miscellaneous,actor","tt15261252,tt1399664,tt6474236,tt6878882",assistant_director,"miscellaneous,actor"
1106394,nm9988620,Titus I. Jackson,\N,\N,"cinematographer,director,writer","tt14030682,tt8732432,tt10627474",cinematographer,"director,writer"
1106422,nm9989001,Hyun-jin Ma,\N,\N,director,\N,director,NaN
1106429,nm9989068,Alice Zanini,\N,\N,"actress,assistant_director","tt5263880,tt7802180,tt9829282,tt11876490",actress,assistant_director
1106432,nm9989234,Happy BanMajra,\N,\N,"actor,assistant_director,production_manager","tt13823812,tt8733862,tt9537936,tt13134002",actor,"assistant_director,production_manager"
1106439,nm9989277,Ryan Manley,\N,\N,"writer,director,casting_director","tt9615610,tt10749930,tt8734436,tt12264946",writer,"director,casting_director"
1106443,nm9989631,Ellie Madden,\N,\N,"actress,assistant_director,stunts","tt8735428,tt9578208",actress,"assistant_director,stunts"
1106472,nm9990253,Dennis Mallen,\N,\N,"actor,producer,assistant_director","tt10746060,tt14140642,tt11388622,tt13650596",actor,"producer,assistant_director"
1106492,nm9990679,Jude Okwudiafor Johnson,\N,\N,"producer,director,actor",\N,producer,"director,actor"
1106504,nm9991134,Hasshi,\N,\N,director,"tt9585424,tt9883900,tt13499386,tt8737918",director,NaN
1106507,nm9991166,Brian Corso,\N,\N,"producer,director,executive","tt10047438,tt10832454,tt12803088,tt8738176",producer,"director,executive"
1106516,nm9991402,Eric Sturges,\N,\N,"writer,producer,director","tt8734436,tt10802798,tt9078846,tt12264946",writer,"producer,director"
1106517,nm9991404,Lisa Morel,\N,\N,"casting_director,producer,casting_department","tt8431754,tt10495908,tt9615610,tt8734436",casting_director,"producer,casting_department"
1106518,nm9991412,Taylor Katsanis,\N,\N,"director,actor,editor","tt12570876,tt9518982,tt12113548,tt8738578",director,"actor,editor"
1106540,nm9992067,Robert DeBoucher,\N,\N,"editor,director,writer","tt11026620,tt10770776,tt8923476",editor,"director,writer"
1106551,nm9992429,Haley Elizabeth Anderson,\N,\N,"director,writer,producer","tt11685322,tt11695844,tt14040068,tt12564956",director,"writer,producer"
1106560,nm9992590,Rock White,\N,\N,"sound_department,camera_department,director","tt13750234,tt13601662,tt9188928,tt10399238",sound_department,"camera_department,director"
1106563,nm9992639,Donnie Dodge,\N,\N,"director,writer,producer","tt11577388,tt10645746,tt8741948,tt14855720",director,"writer,producer"
1106570,nm9992757,Bardia Zeinali,\N,\N,director,tt15285682,director,NaN
1106571,nm9992763,Pedro Flores Maldonado,\N,\N,"director,cinematographer","tt8742174,tt11734696",director,cinematographer
1106573,nm9992818,Dudley Wineriter,\N,\N,"actor,producer,assistant_director","tt13814986,tt8742432,tt14136100,tt11183642",actor,"producer,assistant_director"
1106574,nm9992819,Jennifer DiBlasio,\N,\N,"actress,assistant_director","tt13814986,tt13404996,tt14297962,tt14287002",actress,assistant_director
1106580,nm9992900,Tin Brendel,\N,\N,"writer,director,cinematographer",\N,writer,"director,cinematographer"
1106582,nm9992905,Hepi Mita,\N,\N,"director,camera_department","tt8742574,tt1504286",director,camera_department
1106583,nm9992929,Krista Riihimaki,\N,\N,"director,writer,cinematographer",tt8742604,director,"writer,cinematographer"
1106613,nm9993594,Adeoluwa Owu,\N,\N,"cinematographer,director,camera_department","tt16253232,tt16423720,tt15892144,tt13204624",cinematographer,"director,camera_department"

In [99]:
director = director.join(director['primaryProfession'].str.split(',', expand=True).rename(columns={0:'Job1', 1:'Job2', 2:'Job3'}))

In [100]:
director = director[['nconst', 'primaryName', 'birthYear', 'deathYear', 'primaryProfession', 'knownForTitles', 'Job1', 'Job2' , 'Job3']]

In [104]:
director = director[['nconst', 'primaryName', 'birthYear', 'deathYear', 'knownForTitles']]

In [105]:
director

,nconst,primaryName,birthYear,deathYear,knownForTitles
4,nm0000005,Ingmar Bergman,1918,2007,"tt0069467,tt0083922,tt0060827,tt0050986"
7,nm0000008,Marlon Brando,1924,2004,"tt0078788,tt0070849,tt0047296,tt0068646"
9,nm0000010,James Cagney,1899,1986,"tt0031867,tt0029870,tt0035575,tt0042041"
18,nm0000019,Federico Fellini,1920,1993,"tt0050783,tt0047528,tt0071129,tt0056801"
23,nm0000024,John Gielgud,1904,2000,"tt0071877,tt0082031,tt0117631,tt0045943"
31,nm0000032,Charlton Heston,1923,2008,"tt0052618,tt0063442,tt0049833,tt0070723"
32,nm0000033,Alfred Hitchcock,1899,1980,"tt0052357,tt0053125,tt0056869,tt0054215"
35,nm0000036,Buster Keaton,1895,1966,"tt0015324,tt0016332,tt0017925,tt0019421"
36,nm0000037,Gene Kelly,1912,1996,"tt0041716,tt0053946,tt0043278,tt0045152"
39,nm0000040,Stanley Kubrick,1928,1999,"tt0120663,tt0072684,tt0066921,tt0062622"
40,nm0000041,Akira Kurosawa,1910,1998,"tt0089881,tt0080979,tt0051808,tt0057565"
55,nm0000056,Paul Newman,1925,2008,"tt0084855,tt0257044,tt0054997,tt0061512"
58,nm0000059,Laurence Olivier,1907,1989,"tt0077269,tt0074860,tt0032976,tt0069281"
70,nm0000071,James Stewart,1908,1997,"tt0052561,tt0052357,tt0032904,tt0031679"
75,nm0000076,François Truffaut,1932,1984,"tt0075860,tt0070460,tt0055032,tt0053198"
79,nm0000080,Orson Welles,1915,1985,"tt0038991,tt0040525,tt0033467,tt0052311"
82,nm0000083,Alan Miller,\N,\N,"tt0969216,tt5969604,tt0424773,tt0320978"
86,nm0000087,Elena Koreneva,1953,\N,"tt5847740,tt7529350,tt0080912,tt0122969"
87,nm0000088,Aleksey Korenev,1927,1995,"tt0063752,tt0068304,tt0100069,tt0191104"
89,nm0000090,Armin Mueller-Stahl,1930,\N,"tt0139809,tt0117631,tt0963178,tt0765443"
90,nm0000091,Gérard Pirès,1942,\N,"tt0152930,tt0282552,tt0064297,tt0374627"
94,nm0000095,Woody Allen,1935,\N,"tt0075686,tt0097123,tt0079522,tt0091167"
96,nm0000097,Pamela Anderson,1967,\N,"tt0426592,tt0115624,tt0306047,tt0267913"
98,nm0000099,Patricia Arquette,1968,\N,"tt0108399,tt0412175,tt1065073,tt0145531"
107,nm0000108,Luc Besson,1959,\N,"tt0119116,tt0110413,tt2872732,tt0100263"
109,nm0000110,Kenneth Branagh,1960,\N,"tt0116477,tt0097499,tt3402236,tt0107616"
110,nm0000111,Matthew Broderick,1962,\N,"tt0086567,tt0091042,tt0126886,tt0395251"
113,nm0000114,Steve Buscemi,1957,\N,"tt0105236,tt4686844,tt0116282,tt0162346"
115,nm0000116,James Cameron,1954,\N,"tt0090605,tt0120338,tt0499549,tt0103064"
122,nm0000123,George Clooney,1961,\N,"tt0465538,tt0433383,tt1193138,tt1124035"
...,...,...,...,...,...
1106379,nm9988015,Jathin Sanker Raj,\N,\N,"tt9536990,tt8731842"
1106385,nm9988424,Mohamed Hesham El-Rashidy,\N,\N,tt11493006
1106387,nm9988432,Kumar Gangappan,\N,\N,"tt7738784,tt11216522,tt12472554,tt4701664"
1106389,nm9988460,David Sincere Aiken,\N,\N,"tt2473602,tt5030402"
1106391,nm9988491,Hicham Goullal,\N,\N,"tt15261252,tt1399664,tt6474236,tt6878882"
1106394,nm9988620,Titus I. Jackson,\N,\N,"tt14030682,tt8732432,tt10627474"
1106422,nm9989001,Hyun-jin Ma,\N,\N,\N
1106429,nm9989068,Alice Zanini,\N,\N,"tt5263880,tt7802180,tt9829282,tt11876490"
1106432,nm9989234,Happy BanMajra,\N,\N,"tt13823812,tt8733862,tt9537936,tt13134002"
1106439,nm9989277,Ryan Manley,\N,\N,"tt9615610,tt10749930,tt8734436,tt12264946"
1106443,nm9989631,Ellie Madden,\N,\N,"tt8735428,tt9578208"
1106472,nm9990253,Dennis Mallen,\N,\N,"tt10746060,tt14140642,tt11388622,tt13650596"
1106492,nm9990679,Jude Okwudiafor Johnson,\N,\N,\N
1106504,nm9991134,Hasshi,\N,\N,"tt9585424,tt9883900,tt13499386,tt8737918"
1106507,nm9991166,Brian Corso,\N,\N,"tt10047438,tt10832454,tt12803088,tt8738176"
1106516,nm9991402,Eric Sturges,\N,\N,"tt8734436,tt10802798,tt9078846,tt12264946"
1106517,nm9991404,Lisa Morel,\N,\N,"tt8431754,tt10495908,tt9615610,tt8734436"
1106518,nm9991412,Taylor Katsanis,\N,\N,"tt12570876,tt9518982,tt12113548,tt8738578"
1106540,nm9992067,Robert DeBoucher,\N,\N,"tt11026620,tt10770776,tt8923476"
1106551,nm9992429,Haley Elizabeth Anderson,\N,\N,"tt11685322,tt11695844,tt14040068,tt12564956"
1106560,nm9992590,Rock White,\N,\N,"tt13750234,tt13601662,tt9188928,tt10399238"
1106563,nm9992639,Donnie Dodge,\N,\N,"tt11577388,tt10645746,tt8741948,tt14855720"
1106570,nm9992757,Bardia Zeinali,\N,\N,tt15285682
1106571,nm9992763,Pedro Flores Maldonado,\N,\N,"tt8742174,tt11734696"
1106573,nm9992818,Dudley Wineriter,\N,\N,"tt13814986,tt8742432,tt14136100,tt11183642"
1106574,nm9992819,Jennifer DiBlasio,\N,\N,"tt13814986,tt13404996,tt14297962,tt14287002"
1106580,nm9992900,Tin Brendel,\N,\N,\N
1106582,nm9992905,Hepi Mita,\N,\N,"tt8742574,tt1504286"
1106583,nm9992929,Krista Riihimaki,\N,\N,tt8742604
1106613,nm9993594,Adeoluwa Owu,\N,\N,"tt16253232,tt16423720,tt15892144,tt13204624"

In [106]:
director = director[director['birthYear'].notnull()]

In [107]:
director

,nconst,primaryName,birthYear,deathYear,knownForTitles
4,nm0000005,Ingmar Bergman,1918,2007,"tt0069467,tt0083922,tt0060827,tt0050986"
7,nm0000008,Marlon Brando,1924,2004,"tt0078788,tt0070849,tt0047296,tt0068646"
9,nm0000010,James Cagney,1899,1986,"tt0031867,tt0029870,tt0035575,tt0042041"
18,nm0000019,Federico Fellini,1920,1993,"tt0050783,tt0047528,tt0071129,tt0056801"
23,nm0000024,John Gielgud,1904,2000,"tt0071877,tt0082031,tt0117631,tt0045943"
31,nm0000032,Charlton Heston,1923,2008,"tt0052618,tt0063442,tt0049833,tt0070723"
32,nm0000033,Alfred Hitchcock,1899,1980,"tt0052357,tt0053125,tt0056869,tt0054215"
35,nm0000036,Buster Keaton,1895,1966,"tt0015324,tt0016332,tt0017925,tt0019421"
36,nm0000037,Gene Kelly,1912,1996,"tt0041716,tt0053946,tt0043278,tt0045152"
39,nm0000040,Stanley Kubrick,1928,1999,"tt0120663,tt0072684,tt0066921,tt0062622"
40,nm0000041,Akira Kurosawa,1910,1998,"tt0089881,tt0080979,tt0051808,tt0057565"
55,nm0000056,Paul Newman,1925,2008,"tt0084855,tt0257044,tt0054997,tt0061512"
58,nm0000059,Laurence Olivier,1907,1989,"tt0077269,tt0074860,tt0032976,tt0069281"
70,nm0000071,James Stewart,1908,1997,"tt0052561,tt0052357,tt0032904,tt0031679"
75,nm0000076,François Truffaut,1932,1984,"tt0075860,tt0070460,tt0055032,tt0053198"
79,nm0000080,Orson Welles,1915,1985,"tt0038991,tt0040525,tt0033467,tt0052311"
82,nm0000083,Alan Miller,\N,\N,"tt0969216,tt5969604,tt0424773,tt0320978"
86,nm0000087,Elena Koreneva,1953,\N,"tt5847740,tt7529350,tt0080912,tt0122969"
87,nm0000088,Aleksey Korenev,1927,1995,"tt0063752,tt0068304,tt0100069,tt0191104"
89,nm0000090,Armin Mueller-Stahl,1930,\N,"tt0139809,tt0117631,tt0963178,tt0765443"
90,nm0000091,Gérard Pirès,1942,\N,"tt0152930,tt0282552,tt0064297,tt0374627"
94,nm0000095,Woody Allen,1935,\N,"tt0075686,tt0097123,tt0079522,tt0091167"
96,nm0000097,Pamela Anderson,1967,\N,"tt0426592,tt0115624,tt0306047,tt0267913"
98,nm0000099,Patricia Arquette,1968,\N,"tt0108399,tt0412175,tt1065073,tt0145531"
107,nm0000108,Luc Besson,1959,\N,"tt0119116,tt0110413,tt2872732,tt0100263"
109,nm0000110,Kenneth Branagh,1960,\N,"tt0116477,tt0097499,tt3402236,tt0107616"
110,nm0000111,Matthew Broderick,1962,\N,"tt0086567,tt0091042,tt0126886,tt0395251"
113,nm0000114,Steve Buscemi,1957,\N,"tt0105236,tt4686844,tt0116282,tt0162346"
115,nm0000116,James Cameron,1954,\N,"tt0090605,tt0120338,tt0499549,tt0103064"
122,nm0000123,George Clooney,1961,\N,"tt0465538,tt0433383,tt1193138,tt1124035"
...,...,...,...,...,...
1106379,nm9988015,Jathin Sanker Raj,\N,\N,"tt9536990,tt8731842"
1106385,nm9988424,Mohamed Hesham El-Rashidy,\N,\N,tt11493006
1106387,nm9988432,Kumar Gangappan,\N,\N,"tt7738784,tt11216522,tt12472554,tt4701664"
1106389,nm9988460,David Sincere Aiken,\N,\N,"tt2473602,tt5030402"
1106391,nm9988491,Hicham Goullal,\N,\N,"tt15261252,tt1399664,tt6474236,tt6878882"
1106394,nm9988620,Titus I. Jackson,\N,\N,"tt14030682,tt8732432,tt10627474"
1106422,nm9989001,Hyun-jin Ma,\N,\N,\N
1106429,nm9989068,Alice Zanini,\N,\N,"tt5263880,tt7802180,tt9829282,tt11876490"
1106432,nm9989234,Happy BanMajra,\N,\N,"tt13823812,tt8733862,tt9537936,tt13134002"
1106439,nm9989277,Ryan Manley,\N,\N,"tt9615610,tt10749930,tt8734436,tt12264946"
1106443,nm9989631,Ellie Madden,\N,\N,"tt8735428,tt9578208"
1106472,nm9990253,Dennis Mallen,\N,\N,"tt10746060,tt14140642,tt11388622,tt13650596"
1106492,nm9990679,Jude Okwudiafor Johnson,\N,\N,\N
1106504,nm9991134,Hasshi,\N,\N,"tt9585424,tt9883900,tt13499386,tt8737918"
1106507,nm9991166,Brian Corso,\N,\N,"tt10047438,tt10832454,tt12803088,tt8738176"
1106516,nm9991402,Eric Sturges,\N,\N,"tt8734436,tt10802798,tt9078846,tt12264946"
1106517,nm9991404,Lisa Morel,\N,\N,"tt8431754,tt10495908,tt9615610,tt8734436"
1106518,nm9991412,Taylor Katsanis,\N,\N,"tt12570876,tt9518982,tt12113548,tt8738578"
1106540,nm9992067,Robert DeBoucher,\N,\N,"tt11026620,tt10770776,tt8923476"
1106551,nm9992429,Haley Elizabeth Anderson,\N,\N,"tt11685322,tt11695844,tt14040068,tt12564956"
1106560,nm9992590,Rock White,\N,\N,"tt13750234,tt13601662,tt9188928,tt10399238"
1106563,nm9992639,Donnie Dodge,\N,\N,"tt11577388,tt10645746,tt8741948,tt14855720"
1106570,nm9992757,Bardia Zeinali,\N,\N,tt15285682
1106571,nm9992763,Pedro Flores Maldonado,\N,\N,"tt8742174,tt11734696"
1106573,nm9992818,Dudley Wineriter,\N,\N,"tt13814986,tt8742432,tt14136100,tt11183642"
1106574,nm9992819,Jennifer DiBlasio,\N,\N,"tt13814986,tt13404996,tt14297962,tt14287002"
1106580,nm9992900,Tin Brendel,\N,\N,\N
1106582,nm9992905,Hepi Mita,\N,\N,"tt8742574,tt1504286"
1106583,nm9992929,Krista Riihimaki,\N,\N,tt8742604
1106613,nm9993594,Adeoluwa Owu,\N,\N,"tt16253232,tt16423720,tt15892144,tt13204624"

In [109]:
director_filtered = director [(director.birthYear != '\\N')]

In [111]:
director_filtered = director_filtered [(director_filtered.knownForTitles != '\\N')]

In [113]:
director_filtered

,nconst,primaryName,birthYear,deathYear,knownForTitles
4,nm0000005,Ingmar Bergman,1918,2007,"tt0069467,tt0083922,tt0060827,tt0050986"
7,nm0000008,Marlon Brando,1924,2004,"tt0078788,tt0070849,tt0047296,tt0068646"
9,nm0000010,James Cagney,1899,1986,"tt0031867,tt0029870,tt0035575,tt0042041"
18,nm0000019,Federico Fellini,1920,1993,"tt0050783,tt0047528,tt0071129,tt0056801"
23,nm0000024,John Gielgud,1904,2000,"tt0071877,tt0082031,tt0117631,tt0045943"
31,nm0000032,Charlton Heston,1923,2008,"tt0052618,tt0063442,tt0049833,tt0070723"
32,nm0000033,Alfred Hitchcock,1899,1980,"tt0052357,tt0053125,tt0056869,tt0054215"
35,nm0000036,Buster Keaton,1895,1966,"tt0015324,tt0016332,tt0017925,tt0019421"
36,nm0000037,Gene Kelly,1912,1996,"tt0041716,tt0053946,tt0043278,tt0045152"
39,nm0000040,Stanley Kubrick,1928,1999,"tt0120663,tt0072684,tt0066921,tt0062622"
40,nm0000041,Akira Kurosawa,1910,1998,"tt0089881,tt0080979,tt0051808,tt0057565"
55,nm0000056,Paul Newman,1925,2008,"tt0084855,tt0257044,tt0054997,tt0061512"
58,nm0000059,Laurence Olivier,1907,1989,"tt0077269,tt0074860,tt0032976,tt0069281"
70,nm0000071,James Stewart,1908,1997,"tt0052561,tt0052357,tt0032904,tt0031679"
75,nm0000076,François Truffaut,1932,1984,"tt0075860,tt0070460,tt0055032,tt0053198"
79,nm0000080,Orson Welles,1915,1985,"tt0038991,tt0040525,tt0033467,tt0052311"
86,nm0000087,Elena Koreneva,1953,\N,"tt5847740,tt7529350,tt0080912,tt0122969"
87,nm0000088,Aleksey Korenev,1927,1995,"tt0063752,tt0068304,tt0100069,tt0191104"
89,nm0000090,Armin Mueller-Stahl,1930,\N,"tt0139809,tt0117631,tt0963178,tt0765443"
90,nm0000091,Gérard Pirès,1942,\N,"tt0152930,tt0282552,tt0064297,tt0374627"
94,nm0000095,Woody Allen,1935,\N,"tt0075686,tt0097123,tt0079522,tt0091167"
96,nm0000097,Pamela Anderson,1967,\N,"tt0426592,tt0115624,tt0306047,tt0267913"
98,nm0000099,Patricia Arquette,1968,\N,"tt0108399,tt0412175,tt1065073,tt0145531"
107,nm0000108,Luc Besson,1959,\N,"tt0119116,tt0110413,tt2872732,tt0100263"
109,nm0000110,Kenneth Branagh,1960,\N,"tt0116477,tt0097499,tt3402236,tt0107616"
110,nm0000111,Matthew Broderick,1962,\N,"tt0086567,tt0091042,tt0126886,tt0395251"
113,nm0000114,Steve Buscemi,1957,\N,"tt0105236,tt4686844,tt0116282,tt0162346"
115,nm0000116,James Cameron,1954,\N,"tt0090605,tt0120338,tt0499549,tt0103064"
122,nm0000123,George Clooney,1961,\N,"tt0465538,tt0433383,tt1193138,tt1124035"
126,nm0000127,Wes Craven,1939,2015,"tt0111686,tt0117571,tt0087800,tt0105121"
...,...,...,...,...,...
1098248,nm9801194,Tori Piskin,1991,\N,"tt10843330,tt12828134,tt3278540"
1098613,nm9808852,Riccardo Vecchione,1973,\N,"tt9617588,tt8361898"
1098743,nm9811757,Artur Krzysztof Wojnowski,1984,\N,"tt8360906,tt11109170"
1099211,nm9822757,Sonu Sinha,2002,\N,"tt5764096,tt9558468,tt4387040,tt2077833"
1099507,nm9828766,Carlo Baltazar,1985,\N,"tt15470248,tt13243170,tt15333510,tt14293146"
1099615,nm9831418,Myles Wright,1997,\N,"tt12036184,tt11348570,tt12616296,tt3645318"
1099700,nm9833890,Erik Felderhof,1984,\N,"tt13090994,tt10627300,tt8386690"
1099706,nm9834016,Lucia Kasová,1983,\N,"tt15762322,tt14391352,tt10564760,tt9497264"
1099750,nm9835035,Lil D,1999,\N,"tt8295332,tt4863818,tt11481408,tt14636122"
1100183,nm9845146,Uttar Kumar,1973,\N,"tt11624506,tt11617422,tt10346016,tt11963556"
1100387,nm9850643,Alexander Geil,2003,\N,"tt8438954,tt13287512,tt8829832,tt10873874"
1100767,nm9858460,Veta Geraskina,1986,\N,"tt5243340,tt8454312,tt10443416,tt10481890"
1101296,nm9870890,Ashley Alban,1994,\N,"tt8482464,tt13198896"
1101298,nm9870916,Ginger Banks,1990,\N,"tt13559776,tt7817662,tt13198896,tt8475784"
1101499,nm9875300,David Thian,1977,\N,"tt9053072,tt8555576"
1101885,nm9883705,Shane Fleming,2003,\N,"tt16900004,tt8174412,tt8518310,tt14057586"
1102036,nm9887703,Marc Blasweiler,1969,\N,tt8514324
1102158,nm9891101,Benjamin Rothman,1896,1973,tt8521670
1102482,nm9897793,Harish Arora,1949,\N,tt8537562
1103127,nm9911310,Sherill Quinn,1989,\N,"tt14928208,tt15752062,tt13763404,tt9525946"
1103872,nm9928618,Roberto Farías,1969,\N,"tt8274328,tt4375438,tt1863321,tt3328948"
1103911,nm9929059,Diego Rezende,1992,\N,"tt9000454,tt7312258,tt7957908,tt12048384"
1104046,nm9932329,Jake Sidney Cohen,1992,\N,"tt11423420,tt7008682"
1104475,nm9941870,Ruby Ibarra,1991,\N,"tt4558716,tt14850172,tt10550754"
1104634,nm9946633,Mateusz Pacewicz,1992,\N,"tt8649186,tt9506474,tt8680242,tt12879304"
1104691,nm9947902,Anna Pawluczuk,1991,\N,"tt9506474,tt11151980,tt8890406,tt8651806"
1104803,nm9951989,Jakub Prysak,1993,\N,"tt15075324,tt15075396,tt8659748,tt10244550"
1104906,nm9955962,Christian Vogel,1981,\N,"tt0463849,tt0289801,tt5510950,tt8666494"
1104999,nm9957570,Manele Labidi,1982,\N,"tt9648886,tt0341901,tt8750728,tt0390699"
1105513,nm9968056,Joël Dupont,1990,\N,"tt12607630,tt6192896,tt11394340,tt10233884"

In [114]:
director_filtered.to_csv('director_filtered_NoNULLBirthYear_NoNULLTitle.csv', index=False)

In [115]:
director_filtered = director_filtered.join(director_filtered['knownForTitles'].str.split(',', expand=True).rename(columns={0:'Title1', 1:'Title2', 2:'Title3', 3:'Title4'}))

In [116]:
director_filtered

,nconst,primaryName,birthYear,deathYear,knownForTitles,Title1,Title2,Title3,Title4
4,nm0000005,Ingmar Bergman,1918,2007,"tt0069467,tt0083922,tt0060827,tt0050986",tt0069467,tt0083922,tt0060827,tt0050986
7,nm0000008,Marlon Brando,1924,2004,"tt0078788,tt0070849,tt0047296,tt0068646",tt0078788,tt0070849,tt0047296,tt0068646
9,nm0000010,James Cagney,1899,1986,"tt0031867,tt0029870,tt0035575,tt0042041",tt0031867,tt0029870,tt0035575,tt0042041
18,nm0000019,Federico Fellini,1920,1993,"tt0050783,tt0047528,tt0071129,tt0056801",tt0050783,tt0047528,tt0071129,tt0056801
23,nm0000024,John Gielgud,1904,2000,"tt0071877,tt0082031,tt0117631,tt0045943",tt0071877,tt0082031,tt0117631,tt0045943
31,nm0000032,Charlton Heston,1923,2008,"tt0052618,tt0063442,tt0049833,tt0070723",tt0052618,tt0063442,tt0049833,tt0070723
32,nm0000033,Alfred Hitchcock,1899,1980,"tt0052357,tt0053125,tt0056869,tt0054215",tt0052357,tt0053125,tt0056869,tt0054215
35,nm0000036,Buster Keaton,1895,1966,"tt0015324,tt0016332,tt0017925,tt0019421",tt0015324,tt0016332,tt0017925,tt0019421
36,nm0000037,Gene Kelly,1912,1996,"tt0041716,tt0053946,tt0043278,tt0045152",tt0041716,tt0053946,tt0043278,tt0045152
39,nm0000040,Stanley Kubrick,1928,1999,"tt0120663,tt0072684,tt0066921,tt0062622",tt0120663,tt0072684,tt0066921,tt0062622
40,nm0000041,Akira Kurosawa,1910,1998,"tt0089881,tt0080979,tt0051808,tt0057565",tt0089881,tt0080979,tt0051808,tt0057565
55,nm0000056,Paul Newman,1925,2008,"tt0084855,tt0257044,tt0054997,tt0061512",tt0084855,tt0257044,tt0054997,tt0061512
58,nm0000059,Laurence Olivier,1907,1989,"tt0077269,tt0074860,tt0032976,tt0069281",tt0077269,tt0074860,tt0032976,tt0069281
70,nm0000071,James Stewart,1908,1997,"tt0052561,tt0052357,tt0032904,tt0031679",tt0052561,tt0052357,tt0032904,tt0031679
75,nm0000076,François Truffaut,1932,1984,"tt0075860,tt0070460,tt0055032,tt0053198",tt0075860,tt0070460,tt0055032,tt0053198
79,nm0000080,Orson Welles,1915,1985,"tt0038991,tt0040525,tt0033467,tt0052311",tt0038991,tt0040525,tt0033467,tt0052311
86,nm0000087,Elena Koreneva,1953,\N,"tt5847740,tt7529350,tt0080912,tt0122969",tt5847740,tt7529350,tt0080912,tt0122969
87,nm0000088,Aleksey Korenev,1927,1995,"tt0063752,tt0068304,tt0100069,tt0191104",tt0063752,tt0068304,tt0100069,tt0191104
89,nm0000090,Armin Mueller-Stahl,1930,\N,"tt0139809,tt0117631,tt0963178,tt0765443",tt0139809,tt0117631,tt0963178,tt0765443
90,nm0000091,Gérard Pirès,1942,\N,"tt0152930,tt0282552,tt0064297,tt0374627",tt0152930,tt0282552,tt0064297,tt0374627
94,nm0000095,Woody Allen,1935,\N,"tt0075686,tt0097123,tt0079522,tt0091167",tt0075686,tt0097123,tt0079522,tt0091167
96,nm0000097,Pamela Anderson,1967,\N,"tt0426592,tt0115624,tt0306047,tt0267913",tt0426592,tt0115624,tt0306047,tt0267913
98,nm0000099,Patricia Arquette,1968,\N,"tt0108399,tt0412175,tt1065073,tt0145531",tt0108399,tt0412175,tt1065073,tt0145531
107,nm0000108,Luc Besson,1959,\N,"tt0119116,tt0110413,tt2872732,tt0100263",tt0119116,tt0110413,tt2872732,tt0100263
109,nm0000110,Kenneth Branagh,1960,\N,"tt0116477,tt0097499,tt3402236,tt0107616",tt0116477,tt0097499,tt3402236,tt0107616
110,nm0000111,Matthew Broderick,1962,\N,"tt0086567,tt0091042,tt0126886,tt0395251",tt0086567,tt0091042,tt0126886,tt0395251
113,nm0000114,Steve Buscemi,1957,\N,"tt0105236,tt4686844,tt0116282,tt0162346",tt0105236,tt4686844,tt0116282,tt0162346
115,nm0000116,James Cameron,1954,\N,"tt0090605,tt0120338,tt0499549,tt0103064",tt0090605,tt0120338,tt0499549,tt0103064
122,nm0000123,George Clooney,1961,\N,"tt0465538,tt0433383,tt1193138,tt1124035",tt0465538,tt0433383,tt1193138,tt1124035
126,nm0000127,Wes Craven,1939,2015,"tt0111686,tt0117571,tt0087800,tt0105121",tt0111686,tt0117571,tt0087800,tt0105121
...,...,...,...,...,...,...,...,...,...
1098248,nm9801194,Tori Piskin,1991,\N,"tt10843330,tt12828134,tt3278540",tt10843330,tt12828134,tt3278540,None
1098613,nm9808852,Riccardo Vecchione,1973,\N,"tt9617588,tt8361898",tt9617588,tt8361898,None,None
1098743,nm9811757,Artur Krzysztof Wojnowski,1984,\N,"tt8360906,tt11109170",tt8360906,tt11109170,None,None
1099211,nm9822757,Sonu Sinha,2002,\N,"tt5764096,tt9558468,tt4387040,tt2077833",tt5764096,tt9558468,tt4387040,tt2077833
1099507,nm9828766,Carlo Baltazar,1985,\N,"tt15470248,tt13243170,tt15333510,tt14293146",tt15470248,tt13243170,tt15333510,tt14293146
1099615,nm9831418,Myles Wright,1997,\N,"tt12036184,tt11348570,tt12616296,tt3645318",tt12036184,tt11348570,tt12616296,tt3645318
1099700,nm9833890,Erik Felderhof,1984,\N,"tt13090994,tt10627300,tt8386690",tt13090994,tt10627300,tt8386690,None
1099706,nm9834016,Lucia Kasová,1983,\N,"tt15762322,tt14391352,tt10564760,tt9497264",tt15762322,tt14391352,tt10564760,tt9497264
1099750,nm9835035,Lil D,1999,\N,"tt8295332,tt4863818,tt11481408,tt14636122",tt8295332,tt4863818,tt11481408,tt14636122
1100183,nm9845146,Uttar Kumar,1973,\N,"tt11624506,tt11617422,tt10346016,tt11963556",tt11624506,tt11617422,tt10346016,tt11963556
1100387,nm9850643,Alexander Geil,2003,\N,"tt8438954,tt13287512,tt8829832,tt10873874",tt8438954,tt13287512,tt8829832,tt10873874
1100767,nm9858460,Veta Geraskina,1986,\N,"tt5243340,tt8454312,tt10443416,tt10481890",tt5243340,tt8454312,tt10443416,tt10481890
1101296,nm9870890,Ashley Alban,1994,\N,"tt8482464,tt13198896",tt8482464,tt13198896,None,None
1101298,nm9870916,Ginger Banks,1990,\N,"tt13559776,tt7817662,tt13198896,tt8475784",tt13559776,tt7817662,tt13198896,tt8475784
1101499,nm9875300,David Thian,1977,\N,"tt9053072,tt8555576",tt9053072,tt8555576,None,None
1101885,nm9883705,Shane Fleming,2003,\N,"tt16900004,tt8174412,tt8518310,tt14057586",tt16900004,tt8174412,tt8518310,tt14057586
1102036,nm9887703,Marc Blasweiler,1969,\N,tt8514324,tt8514324,None,None,None
1102158,nm9891101,Benjamin Rothman,1896,1973,tt8521670,tt8521670,None,None,None
1102482,nm9897793,Harish Arora,1949,\N,tt8537562,tt8537562,None,None,None
1103127,nm9911310,Sherill Quinn,1989,\N,"tt14928208,tt15752062,tt13763404,tt9525946",tt14928208,tt15752062,tt13763404,tt9525946
1103872,nm9928618,Roberto Farías,1969,\N,"tt8274328,tt4375438,tt1863321,tt3328948",tt8274328,tt4375438,tt1863321,tt3328948
1103911,nm9929059,Diego Rezende,1992,\N,"tt9000454,tt7312258,tt7957908,tt12048384",tt9000454,tt7312258,tt7957908,tt12048384
1104046,nm9932329,Jake Sidney Cohen,1992,\N,"tt11423420,tt7008682",tt11423420,tt7008682,None,None
1104475,nm9941870,Ruby Ibarra,1991,\N,"tt4558716,tt14850172,tt10550754",tt4558716,tt14850172,tt10550754,None
1104634,nm9946633,Mateusz Pacewicz,1992,\N,"tt8649186,tt9506474,tt8680242,tt12879304",tt8649186,tt9506474,tt8680242,tt12879304
1104691,nm9947902,Anna Pawluczuk,1991,\N,"tt9506474,tt11151980,tt8890406,tt8651806",tt9506474,tt11151980,tt8890406,tt8651806
1104803,nm9951989,Jakub Prysak,1993,\N,"tt15075324,tt15075396,tt8659748,tt10244550",tt15075324,tt15075396,tt8659748,tt10244550
1104906,nm9955962,Christian Vogel,1981,\N,"tt0463849,tt0289801,tt5510950,tt8666494",tt0463849,tt0289801,tt5510950,tt8666494
1104999,nm9957570,Manele Labidi,1982,\N,"tt9648886,tt0341901,tt8750728,tt0390699",tt9648886,tt0341901,tt8750728,tt0390699
1105513,nm9968056,Joël Dupont,1990,\N,"tt12607630,tt6192896,tt11394340,tt10233884",tt12607630,tt6192896,tt11394340,tt10233884

In [117]:
director_filtered = director_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title1', 'Title2', 'Title3', 'Title4']]

In [118]:
director_filtered

,nconst,primaryName,birthYear,deathYear,Title1,Title2,Title3,Title4
4,nm0000005,Ingmar Bergman,1918,2007,tt0069467,tt0083922,tt0060827,tt0050986
7,nm0000008,Marlon Brando,1924,2004,tt0078788,tt0070849,tt0047296,tt0068646
9,nm0000010,James Cagney,1899,1986,tt0031867,tt0029870,tt0035575,tt0042041
18,nm0000019,Federico Fellini,1920,1993,tt0050783,tt0047528,tt0071129,tt0056801
23,nm0000024,John Gielgud,1904,2000,tt0071877,tt0082031,tt0117631,tt0045943
31,nm0000032,Charlton Heston,1923,2008,tt0052618,tt0063442,tt0049833,tt0070723
32,nm0000033,Alfred Hitchcock,1899,1980,tt0052357,tt0053125,tt0056869,tt0054215
35,nm0000036,Buster Keaton,1895,1966,tt0015324,tt0016332,tt0017925,tt0019421
36,nm0000037,Gene Kelly,1912,1996,tt0041716,tt0053946,tt0043278,tt0045152
39,nm0000040,Stanley Kubrick,1928,1999,tt0120663,tt0072684,tt0066921,tt0062622
40,nm0000041,Akira Kurosawa,1910,1998,tt0089881,tt0080979,tt0051808,tt0057565
55,nm0000056,Paul Newman,1925,2008,tt0084855,tt0257044,tt0054997,tt0061512
58,nm0000059,Laurence Olivier,1907,1989,tt0077269,tt0074860,tt0032976,tt0069281
70,nm0000071,James Stewart,1908,1997,tt0052561,tt0052357,tt0032904,tt0031679
75,nm0000076,François Truffaut,1932,1984,tt0075860,tt0070460,tt0055032,tt0053198
79,nm0000080,Orson Welles,1915,1985,tt0038991,tt0040525,tt0033467,tt0052311
86,nm0000087,Elena Koreneva,1953,\N,tt5847740,tt7529350,tt0080912,tt0122969
87,nm0000088,Aleksey Korenev,1927,1995,tt0063752,tt0068304,tt0100069,tt0191104
89,nm0000090,Armin Mueller-Stahl,1930,\N,tt0139809,tt0117631,tt0963178,tt0765443
90,nm0000091,Gérard Pirès,1942,\N,tt0152930,tt0282552,tt0064297,tt0374627
94,nm0000095,Woody Allen,1935,\N,tt0075686,tt0097123,tt0079522,tt0091167
96,nm0000097,Pamela Anderson,1967,\N,tt0426592,tt0115624,tt0306047,tt0267913
98,nm0000099,Patricia Arquette,1968,\N,tt0108399,tt0412175,tt1065073,tt0145531
107,nm0000108,Luc Besson,1959,\N,tt0119116,tt0110413,tt2872732,tt0100263
109,nm0000110,Kenneth Branagh,1960,\N,tt0116477,tt0097499,tt3402236,tt0107616
110,nm0000111,Matthew Broderick,1962,\N,tt0086567,tt0091042,tt0126886,tt0395251
113,nm0000114,Steve Buscemi,1957,\N,tt0105236,tt4686844,tt0116282,tt0162346
115,nm0000116,James Cameron,1954,\N,tt0090605,tt0120338,tt0499549,tt0103064
122,nm0000123,George Clooney,1961,\N,tt0465538,tt0433383,tt1193138,tt1124035
126,nm0000127,Wes Craven,1939,2015,tt0111686,tt0117571,tt0087800,tt0105121
...,...,...,...,...,...,...,...,...
1098248,nm9801194,Tori Piskin,1991,\N,tt10843330,tt12828134,tt3278540,None
1098613,nm9808852,Riccardo Vecchione,1973,\N,tt9617588,tt8361898,None,None
1098743,nm9811757,Artur Krzysztof Wojnowski,1984,\N,tt8360906,tt11109170,None,None
1099211,nm9822757,Sonu Sinha,2002,\N,tt5764096,tt9558468,tt4387040,tt2077833
1099507,nm9828766,Carlo Baltazar,1985,\N,tt15470248,tt13243170,tt15333510,tt14293146
1099615,nm9831418,Myles Wright,1997,\N,tt12036184,tt11348570,tt12616296,tt3645318
1099700,nm9833890,Erik Felderhof,1984,\N,tt13090994,tt10627300,tt8386690,None
1099706,nm9834016,Lucia Kasová,1983,\N,tt15762322,tt14391352,tt10564760,tt9497264
1099750,nm9835035,Lil D,1999,\N,tt8295332,tt4863818,tt11481408,tt14636122
1100183,nm9845146,Uttar Kumar,1973,\N,tt11624506,tt11617422,tt10346016,tt11963556
1100387,nm9850643,Alexander Geil,2003,\N,tt8438954,tt13287512,tt8829832,tt10873874
1100767,nm9858460,Veta Geraskina,1986,\N,tt5243340,tt8454312,tt10443416,tt10481890
1101296,nm9870890,Ashley Alban,1994,\N,tt8482464,tt13198896,None,None
1101298,nm9870916,Ginger Banks,1990,\N,tt13559776,tt7817662,tt13198896,tt8475784
1101499,nm9875300,David Thian,1977,\N,tt9053072,tt8555576,None,None
1101885,nm9883705,Shane Fleming,2003,\N,tt16900004,tt8174412,tt8518310,tt14057586
1102036,nm9887703,Marc Blasweiler,1969,\N,tt8514324,None,None,None
1102158,nm9891101,Benjamin Rothman,1896,1973,tt8521670,None,None,None
1102482,nm9897793,Harish Arora,1949,\N,tt8537562,None,None,None
1103127,nm9911310,Sherill Quinn,1989,\N,tt14928208,tt15752062,tt13763404,tt9525946
1103872,nm9928618,Roberto Farías,1969,\N,tt8274328,tt4375438,tt1863321,tt3328948
1103911,nm9929059,Diego Rezende,1992,\N,tt9000454,tt7312258,tt7957908,tt12048384
1104046,nm9932329,Jake Sidney Cohen,1992,\N,tt11423420,tt7008682,None,None
1104475,nm9941870,Ruby Ibarra,1991,\N,tt4558716,tt14850172,tt10550754,None
1104634,nm9946633,Mateusz Pacewicz,1992,\N,tt8649186,tt9506474,tt8680242,tt12879304
1104691,nm9947902,Anna Pawluczuk,1991,\N,tt9506474,tt11151980,tt8890406,tt8651806
1104803,nm9951989,Jakub Prysak,1993,\N,tt15075324,tt15075396,tt8659748,tt10244550
1104906,nm9955962,Christian Vogel,1981,\N,tt0463849,tt0289801,tt5510950,tt8666494
1104999,nm9957570,Manele Labidi,1982,\N,tt9648886,tt0341901,tt8750728,tt0390699
1105513,nm9968056,Joël Dupont,1990,\N,tt12607630,tt6192896,tt11394340,tt10233884

In [158]:
Title1 = director_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title1']]

In [124]:
Title2 = director_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title2']]

In [125]:
Title3 = director_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title3']]

In [151]:
Title4 = director_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title4']]

In [160]:
Title1 = Title1[Title1['Title1'].notnull()]

In [155]:
Title2 = Title2[Title2['Title2'].notnull()]

In [156]:
Title3 = Title3[Title3['Title3'].notnull()]

In [157]:
Title4 = Title4[Title4['Title4'].notnull()]

In [ ]:
pandas.concat([Title1, clickDF], ignore_index=True)

In [ ]:
Title1 = Title1

In [165]:
Title1.rename(columns = {'Title1':'Title'}, inplace = True)

In [170]:
Title2.rename(columns = {'Title2':'Title'}, inplace = True)

In [171]:
Title3.rename(columns = {'Title3':'Title'}, inplace = True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3781: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [172]:
Title4.rename(columns = {'Title4':'Title'}, inplace = True)

In [173]:
Title_edited = pandas.concat([Title1, Title2, Title3, Title4], ignore_index=True)

In [178]:
directed_by = Title_edited[['nconst', 'Title']]

In [212]:
directed_by

           nconst       Title
0       nm0000005   tt0069467
1       nm0000008   tt0078788
2       nm0000010   tt0031867
3       nm0000019   tt0050783
4       nm0000024   tt0071877
5       nm0000032   tt0052618
6       nm0000033   tt0052357
7       nm0000036   tt0015324
8       nm0000037   tt0041716
9       nm0000040   tt0120663
10      nm0000041   tt0089881
11      nm0000056   tt0084855
12      nm0000059   tt0077269
13      nm0000071   tt0052561
14      nm0000076   tt0075860
15      nm0000080   tt0038991
16      nm0000087   tt5847740
17      nm0000088   tt0063752
18      nm0000090   tt0139809
19      nm0000091   tt0152930
20      nm0000095   tt0075686
21      nm0000097   tt0426592
22      nm0000099   tt0108399
23      nm0000108   tt0119116
24      nm0000110   tt0116477
25      nm0000111   tt0086567
26      nm0000114   tt0105236
27      nm0000116   tt0090605
28      nm0000123   tt0465538
29      nm0000127   tt0111686
...           ...         ...
181964  nm9700612  tt13135862
181965  nm9706638  tt11100342
181966  nm9708793  tt15227426
181967  nm9733428  tt12862902
181968  nm9744786  tt11193798
181969  nm9767356   tt8269126
181970  nm9770943   tt8736450
181971  nm9772771   tt8280514
181972  nm9786192  tt11554864
181973  nm9789661   tt8347782
181974  nm9790258  tt14722012
181975  nm9822757   tt2077833
181976  nm9828766  tt14293146
181977  nm9831418   tt3645318
181978  nm9834016   tt9497264
181979  nm9835035  tt14636122
181980  nm9845146  tt11963556
181981  nm9850643  tt10873874
181982  nm9858460  tt10481890
181983  nm9870916   tt8475784
181984  nm9883705  tt14057586
181985  nm9911310   tt9525946
181986  nm9928618   tt3328948
181987  nm9929059  tt12048384
181988  nm9946633  tt12879304
181989  nm9947902   tt8651806
181990  nm9951989  tt10244550
181991  nm9955962   tt8666494
181992  nm9957570   tt0390699
181993  nm9968056  tt10233884

[181994 rows x 2 columns]

In [180]:
directed_by.to_csv('directed_by.csv', index=False)

In [183]:
writers

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
3,nm0000004,John Belushi,1949,1982,"actor,soundtrack,writer","tt0072562,tt0078723,tt0080455,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0069467,tt0083922,tt0060827,tt0050986"
18,nm0000019,Federico Fellini,1920,1993,"writer,director,assistant_director","tt0050783,tt0047528,tt0071129,tt0056801"
23,nm0000024,John Gielgud,1904,2000,"actor,writer,director","tt0071877,tt0082031,tt0117631,tt0045943"
26,nm0000027,Alec Guinness,1914,2000,"actor,soundtrack,writer","tt0076759,tt0051739,tt0050212,tt0041546"
30,nm0000031,Katharine Hepburn,1907,2003,"actress,soundtrack,writer","tt0043265,tt0063227,tt0032904,tt0082846"
31,nm0000032,Charlton Heston,1923,2008,"actor,director,writer","tt0052618,tt0063442,tt0049833,tt0070723"
35,nm0000036,Buster Keaton,1895,1966,"actor,writer,director","tt0015324,tt0016332,tt0017925,tt0019421"
39,nm0000040,Stanley Kubrick,1928,1999,"writer,director,producer","tt0120663,tt0072684,tt0066921,tt0062622"
40,nm0000041,Akira Kurosawa,1910,1998,"writer,director,assistant_director","tt0089881,tt0080979,tt0051808,tt0057565"
44,nm0000045,Bruce Lee,1940,1973,"actor,writer,miscellaneous","tt0070034,tt0067824,tt0068767,tt0068935"
45,nm0000046,Vivien Leigh,1913,1967,"actress,soundtrack,writer","tt0044081,tt0033238,tt0034272,tt0031381"
47,nm0000048,Peter Lorre,1904,1964,"actor,soundtrack,writer","tt0036613,tt0034583,tt0033870,tt0022100"
49,nm0000050,Groucho Marx,1890,1977,"soundtrack,actor,writer","tt0028772,tt0026778,tt0023969,tt0023027"
50,nm0000051,James Mason,1909,1984,"actor,producer,writer","tt0084855,tt0056193,tt0053125,tt0047522"
53,nm0000054,Marilyn Monroe,1926,1962,"soundtrack,actress,writer","tt0050861,tt0048605,tt0045810,tt0053291"
63,nm0000064,Edward G. Robinson,1893,1973,"actor,soundtrack,writer","tt0040506,tt0070723,tt0036775,tt0038991"
72,nm0000073,Shirley Temple,1928,2014,"actress,soundtrack,writer","tt0030657,tt0028118,tt0016029,tt0031580"
75,nm0000076,François Truffaut,1932,1984,"writer,director,producer","tt0075860,tt0070460,tt0055032,tt0053198"
79,nm0000080,Orson Welles,1915,1985,"actor,director,writer","tt0038991,tt0040525,tt0033467,tt0052311"
82,nm0000083,Alan Miller,\N,\N,"editor,writer,director","tt0969216,tt5969604,tt0424773,tt0320978"
85,nm0000086,Louis de Funès,1914,1983,"actor,writer,soundtrack","tt0079200,tt0064425,tt0069747,tt0074103"
87,nm0000088,Aleksey Korenev,1927,1995,"director,writer,assistant_director","tt0063752,tt0068304,tt0100069,tt0191104"
89,nm0000090,Armin Mueller-Stahl,1930,\N,"actor,director,writer","tt0139809,tt0117631,tt0963178,tt0765443"
90,nm0000091,Gérard Pirès,1942,\N,"director,writer,actor","tt0152930,tt0282552,tt0064297,tt0374627"
91,nm0000092,John Cleese,1939,\N,"actor,writer,producer","tt0071853,tt0085959,tt0095159,tt0063929"
93,nm0000094,J. Reifel,\N,\N,writer,"tt0116030,tt0117915,tt0118886,tt0118631"
94,nm0000095,Woody Allen,1935,\N,"writer,director,actor","tt0075686,tt0097123,tt0079522,tt0091167"
99,nm0000100,Rowan Atkinson,1955,\N,"actor,writer,producer","tt1634122,tt0110357,tt0118689,tt0274166"
100,nm0000101,Dan Aykroyd,1952,\N,"writer,actor,producer","tt0080455,tt0118747,tt0087332,tt0097428"
...,...,...,...,...,...,...
1106439,nm9989277,Ryan Manley,\N,\N,"writer,director,casting_director","tt9615610,tt10749930,tt8734436,tt12264946"
1106455,nm9989944,Jay Doggs,\N,\N,"soundtrack,writer,composer","tt12810612,tt8735866"
1106469,nm9990184,Crystal Loverro,1995,\N,"actress,producer,writer","tt13924374,tt14604100,tt13612246,tt15041834"
1106498,nm9990895,Igor Matytsyn,\N,\N,"cinematographer,writer","tt14988574,tt8737432"
1106513,nm9991320,Madeline Smith,\N,\N,"actress,writer","tt9615610,tt8734436,tt10573710"
1106516,nm9991402,Eric Sturges,\N,\N,"writer,producer,director","tt8734436,tt10802798,tt9078846,tt12264946"
1106521,nm9991619,Pepe Gaytan,\N,\N,writer,tt0137767
1106522,nm9991648,Juliette Valdez,\N,\N,"actress,writer,producer","tt12954074,tt12976056,tt10560778,tt16091856"
1106523,nm9991653,Wojciech Rzehak,\N,\N,writer,"tt12988416,tt8738964"
1106533,nm9991995,Dave-id Dunlosky,\N,\N,"actor,writer",\N
1106534,nm9991996,James F. Russell,\N,\N,"actor,writer",\N
1106535,nm9991997,Tim Thomas,\N,\N,"actor,writer",\N
1106536,nm9991998,Ken Campbell,\N,\N,"actor,writer",\N
1106540,nm9992067,Robert DeBoucher,\N,\N,"editor,director,writer","tt11026620,tt10770776,tt8923476"
1106544,nm9992180,Julia Quinn,\N,\N,"writer,producer","tt9071818,tt0044298,tt8740790,tt0298674"
1106551,nm9992429,Haley Elizabeth Anderson,\N,\N,"director,writer,producer","tt11685322,tt11695844,tt14040068,tt12564956"
1106557,nm9992507,Michelle Cornwell Jordan,\N,\N,"producer,location_management,writer","tt8795730,tt15021976,tt11193480,tt11192442"
1106563,nm9992639,Donnie Dodge,\N,\N,"director,writer,producer","tt11577388,tt10645746,tt8741948,tt14855720"
1106569,nm9992748,Barbara Moore,\N,\N,"writer,producer","tt10472006,tt10831954,tt10473984,tt10471434"
1106572,nm9992764,Julián Zucchi,\N,\N,"actor,producer,writer","tt13902692,tt11734696,tt8101930,tt8742174"
1106579,nm9992899,Ariane Figueiredo,\N,\N,"writer,editorial_department,producer",\N
1106580,nm9992900,Tin Brendel,\N,\N,"writer,director,cinematographer",\N
1106581,nm9992901,Ann Miller,\N,\N,"producer,writer",tt8707728
1106583,nm9992929,Krista Riihimaki,\N,\N,"director,writer,cinematographer",tt8742604
1106593,nm9992999,William Plyler,\N,\N,"producer,actor,writer","tt8483220,tt3239442,tt9413640"
1106598,nm9993103,Brianna Temple,\N,\N,"actress,writer,camera_department","tt7846794,tt9486184,tt9212760,tt9001550"
1106604,nm9993197,Juanjo Braulio,\N,\N,writer,tt8743032
1106605,nm9993311,Sadegh Khoshhal,\N,\N,writer,"tt8743110,tt8743086,tt13344348,tt15249094"
1106606,nm9993398,Oliviero Del Papa,\N,\N,writer,"tt14165314,tt10270592,tt10941386,tt15662942"
1106611,nm9993494,Amjad Ali,\N,\N,writer,tt7722258

In [184]:
writers = writers[['nconst', 'primaryName', 'birthYear', 'deathYear', 'knownForTitles']]

In [185]:
writers = writers[writers['birthYear'].notnull()]

In [187]:
writers_filtered = writers [(writers.birthYear != '\\N')]

In [188]:
writers_filtered = writers_filtered [(writers_filtered.knownForTitles != '\\N')]

In [190]:
writers_filtered = writers_filtered.join(writers_filtered['knownForTitles'].str.split(',', expand=True).rename(columns={0:'Title1', 1:'Title2', 2:'Title3', 3:'Title4'}))

In [192]:
writers_filtered = writers_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title1', 'Title2', 'Title3', 'Title4']]

In [201]:
W_Title1 = writers_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title1']]

In [203]:
W_Title2 = writers_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title2']];

W_Title3 = writers_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title3']];

W_Title4 = writers_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title4']]

In [206]:
W_Title1.rename(columns = {'Title1':'Title'}, inplace = True);

W_Title2.rename(columns = {'Title2':'Title'}, inplace = True);

W_Title3.rename(columns = {'Title3':'Title'}, inplace = True);

W_Title4.rename(columns = {'Title4':'Title'}, inplace = True);

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3781: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [210]:
W_Title_edited = pandas.concat([W_Title1, W_Title2, W_Title3, W_Title4], ignore_index=True)

In [213]:
written_by = W_Title_edited[['nconst', 'Title']]

In [214]:
written_by

           nconst       Title
0       nm0000004   tt0072562
1       nm0000005   tt0069467
2       nm0000019   tt0050783
3       nm0000024   tt0071877
4       nm0000027   tt0076759
5       nm0000031   tt0043265
6       nm0000032   tt0052618
7       nm0000036   tt0015324
8       nm0000040   tt0120663
9       nm0000041   tt0089881
10      nm0000045   tt0070034
11      nm0000046   tt0044081
12      nm0000048   tt0036613
13      nm0000050   tt0028772
14      nm0000051   tt0084855
15      nm0000054   tt0050861
16      nm0000064   tt0040506
17      nm0000073   tt0030657
18      nm0000076   tt0075860
19      nm0000080   tt0038991
20      nm0000086   tt0079200
21      nm0000088   tt0063752
22      nm0000090   tt0139809
23      nm0000091   tt0152930
24      nm0000092   tt0071853
25      nm0000095   tt0075686
26      nm0000100   tt1634122
27      nm0000101   tt0080455
28      nm0000104   tt0112851
29      nm0000108   tt0119116
...           ...         ...
244654  nm9811757        None
244655  nm9814687  tt12335692
244656  nm9820747        None
244657  nm9822757   tt2077833
244658  nm9824567        None
244659  nm9828766  tt14293146
244660  nm9831418   tt3645318
244661  nm9833890        None
244662  nm9834016   tt9497264
244663  nm9845146  tt11963556
244664  nm9857783  tt12990172
244665  nm9858460  tt10481890
244666  nm9862836        None
244667  nm9870951   tt8482464
244668  nm9875384   tt7354440
244669  nm9887703        None
244670  nm9891447   tt8820632
244671  nm9904580  tt14266408
244672  nm9928618   tt3328948
244673  nm9929059  tt12048384
244674  nm9932329        None
244675  nm9936326        None
244676  nm9946633  tt12879304
244677  nm9951989  tt10244550
244678  nm9955962   tt8666494
244679  nm9957570   tt0390699
244680  nm9957717        None
244681  nm9968056  tt10233884
244682  nm9977814  tt16234442
244683  nm9990184  tt15041834

[244684 rows x 2 columns]

In [215]:
written_by.to_csv('written_by.csv', index=False)

In [218]:
actor = actor[['nconst', 'primaryName', 'birthYear', 'deathYear', 'knownForTitles']];

actor = actor[actor['birthYear'].notnull()];

actor_filtered = actor [(actor.birthYear != '\\N')];

actor_filtered = actor_filtered [(actor_filtered.knownForTitles != '\\N')];

actor_filtered.to_csv('actor_filtered_NoNULLBirthYear_NoNULLTitle.csv', index=False);

actor_filtered = actor_filtered.join(actor_filtered['knownForTitles'].str.split(',', expand=True).rename(columns={0:'Title1', 1:'Title2', 2:'Title3', 3:'Title4'}));

actor_filtered = actor_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title1', 'Title2', 'Title3', 'Title4']];

actorTitle1 = actor_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title1']];

actorTitle2 = actor_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title2']];

actorTitle3 = actor_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title3']];

actorTitle4 = actor_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title4']];

actorTitle1 = actorTitle1[actorTitle1['Title1'].notnull()];

actorTitle2 = actorTitle2[actorTitle2['Title2'].notnull()];

actorTitle3 = actorTitle3[actorTitle3['Title3'].notnull()];

actorTitle4 = actorTitle4[actorTitle4['Title4'].notnull()];

actorTitle1.rename(columns = {'Title1':'Title'}, inplace = True);

actorTitle2.rename(columns = {'Title2':'Title'}, inplace = True);

actorTitle3.rename(columns = {'Title3':'Title'}, inplace = True);

actorTitle4.rename(columns = {'Title4':'Title'}, inplace = True);

actorTitle_edited = pandas.concat([Title1, Title2, Title3, Title4], ignore_index=True);

actor_by = actorTitle_edited[['nconst', 'Title']];

In [221]:
actor_by.to_csv('actor_by.csv', index=False)

In [227]:
actor_by

           nconst       Title
0       nm0000005   tt0069467
1       nm0000008   tt0078788
2       nm0000010   tt0031867
3       nm0000019   tt0050783
4       nm0000024   tt0071877
5       nm0000032   tt0052618
6       nm0000033   tt0052357
7       nm0000036   tt0015324
8       nm0000037   tt0041716
9       nm0000040   tt0120663
10      nm0000041   tt0089881
11      nm0000056   tt0084855
12      nm0000059   tt0077269
13      nm0000071   tt0052561
14      nm0000076   tt0075860
15      nm0000080   tt0038991
16      nm0000087   tt5847740
17      nm0000088   tt0063752
18      nm0000090   tt0139809
19      nm0000091   tt0152930
20      nm0000095   tt0075686
21      nm0000097   tt0426592
22      nm0000099   tt0108399
23      nm0000108   tt0119116
24      nm0000110   tt0116477
25      nm0000111   tt0086567
26      nm0000114   tt0105236
27      nm0000116   tt0090605
28      nm0000123   tt0465538
29      nm0000127   tt0111686
...           ...         ...
181964  nm9700612  tt13135862
181965  nm9706638  tt11100342
181966  nm9708793  tt15227426
181967  nm9733428  tt12862902
181968  nm9744786  tt11193798
181969  nm9767356   tt8269126
181970  nm9770943   tt8736450
181971  nm9772771   tt8280514
181972  nm9786192  tt11554864
181973  nm9789661   tt8347782
181974  nm9790258  tt14722012
181975  nm9822757   tt2077833
181976  nm9828766  tt14293146
181977  nm9831418   tt3645318
181978  nm9834016   tt9497264
181979  nm9835035  tt14636122
181980  nm9845146  tt11963556
181981  nm9850643  tt10873874
181982  nm9858460  tt10481890
181983  nm9870916   tt8475784
181984  nm9883705  tt14057586
181985  nm9911310   tt9525946
181986  nm9928618   tt3328948
181987  nm9929059  tt12048384
181988  nm9946633  tt12879304
181989  nm9947902   tt8651806
181990  nm9951989  tt10244550
181991  nm9955962   tt8666494
181992  nm9957570   tt0390699
181993  nm9968056  tt10233884

[181994 rows x 2 columns]

In [223]:
actress = actress[['nconst', 'primaryName', 'birthYear', 'deathYear', 'knownForTitles']];

actress = actress[actress['birthYear'].notnull()];

actress_filtered = actress [(actress.birthYear != '\\N')];

actress_filtered = actress_filtered [(actress_filtered.knownForTitles != '\\N')];

actress_filtered.to_csv('actress_filtered_NoNULLBirthYear_NoNULLTitle.csv', index=False);

actress_filtered = actress_filtered.join(actress_filtered['knownForTitles'].str.split(',', expand=True).rename(columns={0:'Title1', 1:'Title2', 2:'Title3', 3:'Title4'}));

actress_filtered = actress_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title1', 'Title2', 'Title3', 'Title4']];

actressTitle1 = actress_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title1']];

actressTitle2 = actress_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title2']];

actressTitle3 = actress_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title3']];

actressTitle4 = actress_filtered[['nconst', 'primaryName', 'birthYear', 'deathYear', 'Title4']];

actressTitle1 = actressTitle1[actressTitle1['Title1'].notnull()];

actressTitle2 = actressTitle2[actressTitle2['Title2'].notnull()];

actressTitle3 = actressTitle3[actressTitle3['Title3'].notnull()];

actressTitle4 = actressTitle4[actressTitle4['Title4'].notnull()];

actressTitle1.rename(columns = {'Title1':'Title'}, inplace = True);

actressTitle2.rename(columns = {'Title2':'Title'}, inplace = True);

actressTitle3.rename(columns = {'Title3':'Title'}, inplace = True);

actressTitle4.rename(columns = {'Title4':'Title'}, inplace = True);

actressTitle_edited = pandas.concat([Title1, Title2, Title3, Title4], ignore_index=True);

actress_by = actressTitle_edited[['nconst', 'Title']];

In [225]:
actress_by

           nconst       Title
0       nm0000005   tt0069467
1       nm0000008   tt0078788
2       nm0000010   tt0031867
3       nm0000019   tt0050783
4       nm0000024   tt0071877
5       nm0000032   tt0052618
6       nm0000033   tt0052357
7       nm0000036   tt0015324
8       nm0000037   tt0041716
9       nm0000040   tt0120663
10      nm0000041   tt0089881
11      nm0000056   tt0084855
12      nm0000059   tt0077269
13      nm0000071   tt0052561
14      nm0000076   tt0075860
15      nm0000080   tt0038991
16      nm0000087   tt5847740
17      nm0000088   tt0063752
18      nm0000090   tt0139809
19      nm0000091   tt0152930
20      nm0000095   tt0075686
21      nm0000097   tt0426592
22      nm0000099   tt0108399
23      nm0000108   tt0119116
24      nm0000110   tt0116477
25      nm0000111   tt0086567
26      nm0000114   tt0105236
27      nm0000116   tt0090605
28      nm0000123   tt0465538
29      nm0000127   tt0111686
...           ...         ...
181964  nm9700612  tt13135862
181965  nm9706638  tt11100342
181966  nm9708793  tt15227426
181967  nm9733428  tt12862902
181968  nm9744786  tt11193798
181969  nm9767356   tt8269126
181970  nm9770943   tt8736450
181971  nm9772771   tt8280514
181972  nm9786192  tt11554864
181973  nm9789661   tt8347782
181974  nm9790258  tt14722012
181975  nm9822757   tt2077833
181976  nm9828766  tt14293146
181977  nm9831418   tt3645318
181978  nm9834016   tt9497264
181979  nm9835035  tt14636122
181980  nm9845146  tt11963556
181981  nm9850643  tt10873874
181982  nm9858460  tt10481890
181983  nm9870916   tt8475784
181984  nm9883705  tt14057586
181985  nm9911310   tt9525946
181986  nm9928618   tt3328948
181987  nm9929059  tt12048384
181988  nm9946633  tt12879304
181989  nm9947902   tt8651806
181990  nm9951989  tt10244550
181991  nm9955962   tt8666494
181992  nm9957570   tt0390699
181993  nm9968056  tt10233884

[181994 rows x 2 columns]

In [ ]:
actress_by.to_csv('actress_by.csv', index=False)

In [228]:
actor

,nconst,primaryName,birthYear,deathYear,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"tt0053137,tt0031983,tt0050419,tt0072308"
3,nm0000004,John Belushi,1949,1982,"tt0072562,tt0078723,tt0080455,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"tt0069467,tt0083922,tt0060827,tt0050986"
6,nm0000007,Humphrey Bogart,1899,1957,"tt0033870,tt0034583,tt0042593,tt0043265"
7,nm0000008,Marlon Brando,1924,2004,"tt0078788,tt0070849,tt0047296,tt0068646"
8,nm0000009,Richard Burton,1925,1984,"tt0057877,tt0087803,tt0061184,tt0059749"
9,nm0000010,James Cagney,1899,1986,"tt0031867,tt0029870,tt0035575,tt0042041"
10,nm0000011,Gary Cooper,1901,1961,"tt0035896,tt0027996,tt0034167,tt0044706"
14,nm0000015,James Dean,1931,1955,"tt0049261,tt0120956,tt0048028,tt0048545"
17,nm0000018,Kirk Douglas,1916,2020,"tt0043338,tt0043465,tt0049456,tt0054331"
19,nm0000020,Henry Fonda,1905,1982,"tt0082846,tt0051207,tt0032551,tt0050083"
21,nm0000022,Clark Gable,1901,1960,"tt0023382,tt0031381,tt0026752,tt0025316"
23,nm0000024,John Gielgud,1904,2000,"tt0071877,tt0082031,tt0117631,tt0045943"
25,nm0000026,Cary Grant,1904,1986,"tt0034248,tt0056923,tt0048728,tt0053125"
26,nm0000027,Alec Guinness,1914,2000,"tt0076759,tt0051739,tt0050212,tt0041546"
31,nm0000032,Charlton Heston,1923,2008,"tt0052618,tt0063442,tt0049833,tt0070723"
32,nm0000033,Alfred Hitchcock,1899,1980,"tt0052357,tt0053125,tt0056869,tt0054215"
33,nm0000034,William Holden,1918,1981,"tt0074958,tt0047437,tt0046359,tt0043014"
35,nm0000036,Buster Keaton,1895,1966,"tt0015324,tt0016332,tt0017925,tt0019421"
36,nm0000037,Gene Kelly,1912,1996,"tt0041716,tt0053946,tt0043278,tt0045152"
41,nm0000042,Alan Ladd,1913,1964,"tt0038369,tt0035432,tt0039056,tt0046303"
43,nm0000044,Burt Lancaster,1913,1994,"tt0053793,tt0045793,tt0051036,tt0080388"
44,nm0000045,Bruce Lee,1940,1973,"tt0070034,tt0067824,tt0068767,tt0068935"
47,nm0000048,Peter Lorre,1904,1964,"tt0036613,tt0034583,tt0033870,tt0022100"
49,nm0000050,Groucho Marx,1890,1977,"tt0028772,tt0026778,tt0023969,tt0023027"
50,nm0000051,James Mason,1909,1984,"tt0084855,tt0056193,tt0053125,tt0047522"
51,nm0000052,Marcello Mastroianni,1924,1996,"tt0091113,tt0053779,tt0056801,tt0076085"
52,nm0000053,Robert Mitchum,1917,1997,"tt0039689,tt0055824,tt0048424,tt0056197"
55,nm0000056,Paul Newman,1925,2008,"tt0084855,tt0257044,tt0054997,tt0061512"
56,nm0000057,David Niven,1910,1983,"tt0052182,tt0061452,tt0074937,tt0057413"
...,...,...,...,...,...
1106502,nm9991047,Sam,\N,\N,"tt8590474,tt13626470,tt8591668"
1106508,nm9991281,Sandra Allyson,\N,\N,\N
1106509,nm9991282,Reed Harmon,\N,\N,\N
1106510,nm9991283,Tae McMullen,\N,\N,\N
1106511,nm9991284,Brenda Colbreth,\N,\N,\N
1106518,nm9991412,Taylor Katsanis,\N,\N,"tt12570876,tt9518982,tt12113548,tt8738578"
1106533,nm9991995,Dave-id Dunlosky,\N,\N,\N
1106534,nm9991996,James F. Russell,\N,\N,\N
1106535,nm9991997,Tim Thomas,\N,\N,\N
1106536,nm9991998,Ken Campbell,\N,\N,\N
1106541,nm9992091,Paul Benford-Bruce,\N,\N,tt8740540
1106542,nm9992140,Craig Opfer,\N,\N,\N
1106546,nm9992244,Luca Toma,\N,\N,\N
1106549,nm9992344,Sam Shock,1987,\N,"tt15801814,tt6269222,tt13315802,tt4229630"
1106558,nm9992525,Scott Renteria,\N,\N,"tt12733900,tt8741820,tt8795730,tt8829524"
1106564,nm9992659,Daniar Alshinov,\N,\N,"tt11155928,tt17498694,tt13236334,tt14902026"
1106565,nm9992716,Ck Allen,\N,\N,tt4108686
1106566,nm9992720,McMagic Cardenas,\N,\N,tt7233828
1106572,nm9992764,Julián Zucchi,\N,\N,"tt13902692,tt11734696,tt8101930,tt8742174"
1106573,nm9992818,Dudley Wineriter,\N,\N,"tt13814986,tt8742432,tt14136100,tt11183642"
1106575,nm9992820,Chris Arford,\N,\N,\N
1106576,nm9992821,Stephen Lagud,\N,\N,\N
1106577,nm9992822,Tristen Morse,\N,\N,\N
1106584,nm9992934,Cian Coey,\N,\N,tt8742608
1106585,nm9992936,Bryan Bishop,\N,\N,tt8742608
1106586,nm9992937,Keith Daniel,\N,\N,"tt9213602,tt8742608"
1106592,nm9992983,Damien Nichols,\N,\N,tt8742636
1106593,nm9992999,William Plyler,\N,\N,"tt8483220,tt3239442,tt9413640"
1106608,nm9993444,Jason Winter,\N,\N,"tt8743272,tt10540122"
1106614,nm9993616,Ryan Mac Lennan,\N,\N,tt4844148

In [229]:
actress

,nconst,primaryName,birthYear,deathYear,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"tt0053137,tt0031983,tt0050419,tt0072308"
3,nm0000004,John Belushi,1949,1982,"tt0072562,tt0078723,tt0080455,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"tt0069467,tt0083922,tt0060827,tt0050986"
6,nm0000007,Humphrey Bogart,1899,1957,"tt0033870,tt0034583,tt0042593,tt0043265"
7,nm0000008,Marlon Brando,1924,2004,"tt0078788,tt0070849,tt0047296,tt0068646"
8,nm0000009,Richard Burton,1925,1984,"tt0057877,tt0087803,tt0061184,tt0059749"
9,nm0000010,James Cagney,1899,1986,"tt0031867,tt0029870,tt0035575,tt0042041"
10,nm0000011,Gary Cooper,1901,1961,"tt0035896,tt0027996,tt0034167,tt0044706"
14,nm0000015,James Dean,1931,1955,"tt0049261,tt0120956,tt0048028,tt0048545"
17,nm0000018,Kirk Douglas,1916,2020,"tt0043338,tt0043465,tt0049456,tt0054331"
19,nm0000020,Henry Fonda,1905,1982,"tt0082846,tt0051207,tt0032551,tt0050083"
21,nm0000022,Clark Gable,1901,1960,"tt0023382,tt0031381,tt0026752,tt0025316"
23,nm0000024,John Gielgud,1904,2000,"tt0071877,tt0082031,tt0117631,tt0045943"
25,nm0000026,Cary Grant,1904,1986,"tt0034248,tt0056923,tt0048728,tt0053125"
26,nm0000027,Alec Guinness,1914,2000,"tt0076759,tt0051739,tt0050212,tt0041546"
31,nm0000032,Charlton Heston,1923,2008,"tt0052618,tt0063442,tt0049833,tt0070723"
32,nm0000033,Alfred Hitchcock,1899,1980,"tt0052357,tt0053125,tt0056869,tt0054215"
33,nm0000034,William Holden,1918,1981,"tt0074958,tt0047437,tt0046359,tt0043014"
35,nm0000036,Buster Keaton,1895,1966,"tt0015324,tt0016332,tt0017925,tt0019421"
36,nm0000037,Gene Kelly,1912,1996,"tt0041716,tt0053946,tt0043278,tt0045152"
41,nm0000042,Alan Ladd,1913,1964,"tt0038369,tt0035432,tt0039056,tt0046303"
43,nm0000044,Burt Lancaster,1913,1994,"tt0053793,tt0045793,tt0051036,tt0080388"
44,nm0000045,Bruce Lee,1940,1973,"tt0070034,tt0067824,tt0068767,tt0068935"
47,nm0000048,Peter Lorre,1904,1964,"tt0036613,tt0034583,tt0033870,tt0022100"
49,nm0000050,Groucho Marx,1890,1977,"tt0028772,tt0026778,tt0023969,tt0023027"
50,nm0000051,James Mason,1909,1984,"tt0084855,tt0056193,tt0053125,tt0047522"
51,nm0000052,Marcello Mastroianni,1924,1996,"tt0091113,tt0053779,tt0056801,tt0076085"
52,nm0000053,Robert Mitchum,1917,1997,"tt0039689,tt0055824,tt0048424,tt0056197"
55,nm0000056,Paul Newman,1925,2008,"tt0084855,tt0257044,tt0054997,tt0061512"
56,nm0000057,David Niven,1910,1983,"tt0052182,tt0061452,tt0074937,tt0057413"
...,...,...,...,...,...
1106502,nm9991047,Sam,\N,\N,"tt8590474,tt13626470,tt8591668"
1106508,nm9991281,Sandra Allyson,\N,\N,\N
1106509,nm9991282,Reed Harmon,\N,\N,\N
1106510,nm9991283,Tae McMullen,\N,\N,\N
1106511,nm9991284,Brenda Colbreth,\N,\N,\N
1106518,nm9991412,Taylor Katsanis,\N,\N,"tt12570876,tt9518982,tt12113548,tt8738578"
1106533,nm9991995,Dave-id Dunlosky,\N,\N,\N
1106534,nm9991996,James F. Russell,\N,\N,\N
1106535,nm9991997,Tim Thomas,\N,\N,\N
1106536,nm9991998,Ken Campbell,\N,\N,\N
1106541,nm9992091,Paul Benford-Bruce,\N,\N,tt8740540
1106542,nm9992140,Craig Opfer,\N,\N,\N
1106546,nm9992244,Luca Toma,\N,\N,\N
1106549,nm9992344,Sam Shock,1987,\N,"tt15801814,tt6269222,tt13315802,tt4229630"
1106558,nm9992525,Scott Renteria,\N,\N,"tt12733900,tt8741820,tt8795730,tt8829524"
1106564,nm9992659,Daniar Alshinov,\N,\N,"tt11155928,tt17498694,tt13236334,tt14902026"
1106565,nm9992716,Ck Allen,\N,\N,tt4108686
1106566,nm9992720,McMagic Cardenas,\N,\N,tt7233828
1106572,nm9992764,Julián Zucchi,\N,\N,"tt13902692,tt11734696,tt8101930,tt8742174"
1106573,nm9992818,Dudley Wineriter,\N,\N,"tt13814986,tt8742432,tt14136100,tt11183642"
1106575,nm9992820,Chris Arford,\N,\N,\N
1106576,nm9992821,Stephen Lagud,\N,\N,\N
1106577,nm9992822,Tristen Morse,\N,\N,\N
1106584,nm9992934,Cian Coey,\N,\N,tt8742608
1106585,nm9992936,Bryan Bishop,\N,\N,tt8742608
1106586,nm9992937,Keith Daniel,\N,\N,"tt9213602,tt8742608"
1106592,nm9992983,Damien Nichols,\N,\N,tt8742636
1106593,nm9992999,William Plyler,\N,\N,"tt8483220,tt3239442,tt9413640"
1106608,nm9993444,Jason Winter,\N,\N,"tt8743272,tt10540122"
1106614,nm9993616,Ryan Mac Lennan,\N,\N,tt4844148

In [230]:
df_ratings = pandas.read_csv('./ratings.csv')

In [231]:
df_ratings

           tconst  averageRating  numVotes
0       tt0000009            5.9       193
1       tt0000446            6.3        25
2       tt0000574            6.1       750
3       tt0000591            5.2        16
4       tt0000679            5.3        65
5       tt0000969            6.7        25
6       tt0001105            6.5       890
7       tt0001285            5.6        57
8       tt0001321            5.3        55
9       tt0001381            5.4        37
10      tt0001432            5.6        27
11      tt0001482            5.1        78
12      tt0001498            7.7        12
13      tt0001592            5.5        14
14      tt0001614            6.1        26
15      tt0001692            5.3        14
16      tt0001790            6.0        44
17      tt0001877            5.3        69
18      tt0001892            5.9       227
19      tt0001911            4.5        22
20      tt0001915            5.7       114
21      tt0001963            5.5       146
22      tt0001964            6.0        81
23      tt0002029            6.1        57
24      tt0002078            5.0        65
25      tt0002083            6.1       262
26      tt0002101            5.1       529
27      tt0002122            6.2       305
28      tt0002126            6.3        73
29      tt0002130            7.0      2788
...           ...            ...       ...
323027  tt9909940            5.7        40
323028  tt9910602            6.7        11
323029  tt9910606            6.8        12
323030  tt9910728            5.9       817
323031  tt9911196            7.5      3490
323032  tt9913056            6.8        27
323033  tt9913660            5.6        64
323034  tt9913754            7.2      1109
323035  tt9913936            7.2        58
323036  tt9914162            6.2         5
323037  tt9914254            7.1         8
323038  tt9914350            3.5        27
323039  tt9914370            7.5        25
323040  tt9914414            5.4        15
323041  tt9914458            3.1        51
323042  tt9914496            6.6        16
323043  tt9914546            4.1       151
323044  tt9914598            6.3        81
323045  tt9914642            8.3        40
323046  tt9914644            8.2        98
323047  tt9914942            6.9       138
323048  tt9915138            7.6         6
323049  tt9915436            7.4         5
323050  tt9915872            6.9         8
323051  tt9916170            7.2         5
323052  tt9916190            3.6       230
323053  tt9916200            8.3       196
323054  tt9916204            8.2       224
323055  tt9916348            8.5        17
323056  tt9916362            6.4      4394

[323057 rows x 3 columns]

In [235]:
written_by = written_by[written_by['Title'].notnull()]

In [237]:
written_by.to_csv('written_by.csv', index=False)

In [240]:
written_by_new = written_by[['nconst']]

In [243]:
written_by_new = written_by_new.drop_duplicates()

In [244]:
written_by_new.to_csv('writers.csv', index=False)

In [245]:
actor_by_new = actor_by[['nconst']]

In [246]:
actor_by_new = actor_by_new.drop_duplicates()

In [248]:
actor_by_new.to_csv('actors.csv', index=False)

In [252]:
directed_by_new = directed_by[['nconst']]

In [253]:
directed_by_new = directed_by_new.drop_duplicates()

In [254]:
directed_by_new.to_csv('director.csv', index=False)

In [255]:
df_genres = pandas.read_csv('./genres.csv')

In [256]:
df_genres

                            genres
0                    Romance,Short
1                    Short,Western
2       Action,Adventure,Biography
3                            Drama
4                Adventure,Fantasy
5              Drama,History,Short
6                      Drama,Short
7           Biography,Drama,Family
8                  Drama,Short,War
9                              War
10            Fantasy,Sci-Fi,Short
11         Biography,Drama,History
12                           Short
13             Drama,Romance,Short
14                       Short,War
15                   Drama,History
16         Adventure,Drama,Fantasy
17                 Biography,Drama
18         Biography,Drama,Romance
19                     Documentary
20                     History,War
21             Drama,Short,Western
22         Adventure,Drama,Romance
23              Drama,Horror,Short
24               Crime,Drama,Short
25            Drama,Short,Thriller
26                       Drama,War
27              Comedy,Drama,Short
28                    Horror,Short
29                 Adventure,Short
...                            ...
1811      Drama,Mystery,Reality-TV
1812        Drama,Reality-TV,Short
1813             Crime,Fantasy,War
1814       Horror,Musical,Thriller
1815       Fantasy,History,Musical
1816  Adult,Documentary,Reality-TV
1817        Biography,Thriller,War
1818      Crime,History,Reality-TV
1819     Reality-TV,Short,Thriller
1820   Documentary,Sport,Talk-Show
1821         Adventure,Crime,Music
1822         Adventure,Short,Sport
1823         Crime,Mystery,Western
1824                    Family,War
1825     Game-Show,Sport,Talk-Show
1826        Musical,Mystery,Sci-Fi
1827     Comedy,History,Reality-TV
1828    Documentary,Musical,Sci-Fi
1829        Drama,Sci-Fi,Talk-Show
1830      Adventure,History,Sci-Fi
1831      Animation,Horror,Musical
1832     Animation,Horror,Thriller
1833        Family,Sci-Fi,Thriller
1834            Action,Adult,Short
1835     Documentary,Family,Sci-Fi
1836       Biography,Crime,Fantasy
1837   Mystery,Reality-TV,Thriller
1838        History,Horror,Romance
1839     Game-Show,Music,Talk-Show
1840      Biography,Comedy,Mystery

[1841 rows x 1 columns]

In [258]:
df_genreOf = pandas.read_csv('./genreOf.csv')

In [260]:
df_genreOf = df_genreOf.join(df_genreOf['genres'].str.split(',', expand=True).rename(columns={0:'Title1', 1:'Title2', 2:'Title3'}))

In [262]:
df_genreOf = df_genreOf[['tconst', 'Title1', 'Title2', 'Title3']]

In [269]:
df_genreOf1 = df_genreOf[['tconst', 'Title1']];

df_genreOf2 = df_genreOf[['tconst', 'Title2']];

df_genreOf3 = df_genreOf[['tconst', 'Title3']];

df_genreOf1 = df_genreOf1[df_genreOf1['Title1'].notnull()];

df_genreOf2 = df_genreOf2[df_genreOf2['Title2'].notnull()];

df_genreOf3 = df_genreOf3[df_genreOf3['Title3'].notnull()];

df_genreOf1.rename(columns = {'Title1':'Title'}, inplace = True);

df_genreOf2.rename(columns = {'Title2':'Title'}, inplace = True);

df_genreOf3.rename(columns = {'Title3':'Title'}, inplace = True);

df_genreOf_edited = pandas.concat([df_genreOf1, df_genreOf2, df_genreOf3], ignore_index=True);

In [276]:
df_genreOf_edited.drop_duplicates()

           tconst      Title
0       tt0000009    Romance
1       tt0000446      Short
2       tt0000574     Action
3       tt0000591      Drama
4       tt0000679  Adventure
5       tt0000969      Drama
6       tt0001105      Drama
7       tt0001285  Biography
8       tt0001321      Short
9       tt0001381      Drama
10      tt0001432      Drama
11      tt0001482      Drama
12      tt0001498        War
13      tt0001592      Drama
14      tt0001614      Drama
15      tt0001692      Drama
16      tt0001790      Drama
17      tt0001877    Fantasy
18      tt0001892      Drama
19      tt0001911  Biography
20      tt0001915      Drama
21      tt0001963      Drama
22      tt0001964      Drama
23      tt0002029      Short
24      tt0002057      Drama
25      tt0002078      Drama
26      tt0002083      Short
27      tt0002101      Drama
28      tt0002122      Drama
29      tt0002126     Action
...           ...        ...
903123  tt9895024      Sport
903124  tt9896916     Family
903125  tt9897850      Drama
903126  tt9898118      Drama
903127  tt9898858      Crime
903128  tt9899840     Family
903129  tt9899850   Thriller
903130  tt9899922     Sci-Fi
903131  tt9899982      Short
903132  tt9900060      Crime
903133  tt9900092     Sci-Fi
903134  tt9900782   Thriller
903135  tt9900908      Crime
903136  tt9900940   Thriller
903137  tt9901232      Drama
903138  tt9901972   Thriller
903139  tt9903336     Horror
903140  tt9903504     Family
903141  tt9903622     Family
903142  tt9904066      Drama
903143  tt9907782    Mystery
903144  tt9909484      Drama
903145  tt9910164       News
903146  tt9913754    Fantasy
903147  tt9914406      Short
903148  tt9914432   Thriller
903149  tt9914546     Family
903150  tt9914828     Family
903151  tt9915872    Fantasy
903152  tt9916190   Thriller

[903153 rows x 2 columns]

In [271]:
df_genreOf_edited.to_csv('genreOf.csv', index=False)

In [272]:
df_genres = df_genreOf_edited[['Title']]

In [277]:
df_genres_edited = df_genres.drop_duplicates()

In [278]:
df_genres_edited.to_csv('genres.csv', index=False)

In [279]:
df_genreOf_edited.rename(columns = {'Title':'Genre'}, inplace = True);

In [280]:
df_genreOf_edited.to_csv('genreOf.csv', index=False);

In [281]:

df_genres_edited.rename(columns = {'Title':'Genre'}, inplace = True);

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3781: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [282]:
df_genres_edited.to_csv('genres.csv', index=False)

In [283]:
df_genres_edited

             Genre
0          Romance
1            Short
2           Action
3            Drama
4        Adventure
7        Biography
12             War
17         Fantasy
41     Documentary
44         History
52           Crime
59          Comedy
60          Horror
89         Mystery
121        Western
144             \N
1439        Family
1788         Music
2800     Animation
3734        Sci-Fi
4024         Sport
5734      Thriller
6484       Musical
14714    Film-Noir
17840    Talk-Show
17857    Game-Show
19622         News
29898        Adult
33354   Reality-TV

In [290]:
df_person = pandas.read_csv('./name.basics.csv')

In [285]:
df_person.head(10)

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0053137,tt0031983,tt0050419,tt0072308"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0037382,tt0117057,tt0071877,tt0038355"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,soundtrack,music_department","tt0056404,tt0057345,tt0054452,tt0049189"
3,nm0000004,John Belushi,1949,1982,"actor,soundtrack,writer","tt0072562,tt0078723,tt0080455,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0069467,tt0083922,tt0060827,tt0050986"
5,nm0000006,Ingrid Bergman,1915,1982,"actress,soundtrack,producer","tt0077711,tt0034583,tt0038109,tt0036855"
6,nm0000007,Humphrey Bogart,1899,1957,"actor,soundtrack,producer","tt0033870,tt0034583,tt0042593,tt0043265"
7,nm0000008,Marlon Brando,1924,2004,"actor,soundtrack,director","tt0078788,tt0070849,tt0047296,tt0068646"
8,nm0000009,Richard Burton,1925,1984,"actor,soundtrack,producer","tt0057877,tt0087803,tt0061184,tt0059749"
9,nm0000010,James Cagney,1899,1986,"actor,soundtrack,director","tt0031867,tt0029870,tt0035575,tt0042041"

In [292]:
df_person = df_person[df_person['birthYear'].notnull()];

df_person = df_person [(df_person.birthYear != '\\N')];

In [293]:
df_person.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 221542 entries, 0 to 1106607
Data columns (total 6 columns):
nconst               221542 non-null object
primaryName          221542 non-null object
birthYear            221542 non-null object
deathYear            221542 non-null object
primaryProfession    213169 non-null object
knownForTitles       221542 non-null object
dtypes: object(6)
memory usage: 11.8+ MB

In [294]:
df_person = df_person[df_person['knownForTitles'].notnull()];

df_person = df_person [(df_person.knownForTitles != '\\N')];

In [295]:
df_person.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 220816 entries, 0 to 1106607
Data columns (total 6 columns):
nconst               220816 non-null object
primaryName          220816 non-null object
birthYear            220816 non-null object
deathYear            220816 non-null object
primaryProfession    212910 non-null object
knownForTitles       220816 non-null object
dtypes: object(6)
memory usage: 11.8+ MB

In [296]:
df_person.to_csv('persons.csv', index=False)