In [1]:
import pandas

In [3]:
df_movies = pandas.read_csv('./movies.csv')

In [4]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47992 entries, 0 to 47991
Data columns (total 6 columns):
tconst            47992 non-null object
primaryTitle      47992 non-null object
isAdult           47992 non-null int64
startYear         47992 non-null int64
runtimeMinutes    47992 non-null int64
genres            47992 non-null object
dtypes: int64(3), object(3)
memory usage: 2.2+ MB

In [5]:
genreOf = df_movies [['tconst', 'genres']]

In [6]:
genreOf

          tconst                      genres
0      tt0069049                       Drama
1      tt0100275        Comedy,Drama,Fantasy
2      tt0116991                       Drama
3      tt0137204  Adventure,Animation,Comedy
4      tt0137818                          \N
5      tt0176694     Animation,Drama,History
6      tt0191476                      Comedy
7      tt0192528                       Drama
8      tt0230212                       Drama
9      tt0249516  Action,Adventure,Animation
10     tt0276568                Action,Drama
11     tt0285252                      Comedy
12     tt0293069                    Thriller
13     tt0306058                          \N
14     tt0311448               Drama,Romance
15     tt0315642          Action,Crime,Drama
16     tt0323808                Drama,Horror
17     tt0326592                          \N
18     tt0326965      Drama,Mystery,Thriller
19     tt0329539     Adventure,Comedy,Family
20     tt0331312                Comedy,Drama
21     tt0331314  Adventure,Animation,Comedy
22     tt0337692     Adventure,Drama,Romance
23     tt0337926             Biography,Drama
24     tt0339736                      Horror
25     tt0359950      Adventure,Comedy,Drama
26     tt0360556       Drama,Sci-Fi,Thriller
27     tt0365545        Comedy,Drama,Romance
28     tt0365907          Action,Crime,Drama
29     tt0369610     Action,Adventure,Sci-Fi
...          ...                         ...
47962  tt9896916  Adventure,Animation,Family
47963  tt9898086                       Drama
47964  tt9898858         Action,Comedy,Crime
47965  tt9899840     Adventure,Comedy,Family
47966  tt9899850      Crime,Mystery,Thriller
47967  tt9899860              Drama,Thriller
47968  tt9899880                Comedy,Drama
47969  tt9899938                Comedy,Drama
47970  tt9900050                      Comedy
47971  tt9900388                       Drama
47972  tt9900398                       Drama
47973  tt9900688                      Comedy
47974  tt9900748            Action,Adventure
47975  tt9900782       Action,Crime,Thriller
47976  tt9901162            Action,Adventure
47977  tt9902160                       Drama
47978  tt9903890                      Horror
47979  tt9904004                       Drama
47980  tt9904552                      Comedy
47981  tt9904802                         War
47982  tt9906644                Comedy,Drama
47983  tt9908448               Drama,Fantasy
47984  tt9909940                Drama,Family
47985  tt9911196                Comedy,Drama
47986  tt9913660                       Drama
47987  tt9913936                 Crime,Drama
47988  tt9914828        Action,Comedy,Family
47989  tt9915872        Comedy,Drama,Fantasy
47990  tt9916190   Action,Adventure,Thriller
47991  tt9916362               Drama,History

[47992 rows x 2 columns]